/**
 * Auto-generated endpoint tests from the OpenAPI spec.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run `npm run generate:endpoint-tests` to regenerate.
 */

import { describe, expect, it } from "vitest";
import { Configuration } from "../src/index.js";

import { ConnectionsApi } from "../src/index.js";
import { MediaApi } from "../src/index.js";
import { PostsApi } from "../src/index.js";
import { InsightsApi } from "../src/index.js";
import { CommentsApi } from "../src/index.js";
import { EngagementApi } from "../src/index.js";
import { WebhooksApi } from "../src/index.js";

const config = new Configuration({ apiKey: "op_test" });

describe("spec endpoints surface as SDK methods", () => {
  describe("ConnectionsApi", () => {
    it("exposes connectBluesky", () => {
      expect(typeof new ConnectionsApi(config)["connectBluesky"]).toBe("function");
    });
    it("exposes createPinterestBoard", () => {
      expect(typeof new ConnectionsApi(config)["createPinterestBoard"]).toBe("function");
    });
    it("exposes getConnectionStats", () => {
      expect(typeof new ConnectionsApi(config)["getConnectionStats"]).toBe("function");
    });
    it("exposes getTikTokCreatorInfo", () => {
      expect(typeof new ConnectionsApi(config)["getTikTokCreatorInfo"]).toBe("function");
    });
    it("exposes listConnectionMedia", () => {
      expect(typeof new ConnectionsApi(config)["listConnectionMedia"]).toBe("function");
    });
    it("exposes listConnections", () => {
      expect(typeof new ConnectionsApi(config)["listConnections"]).toBe("function");
    });
    it("exposes listFacebookPages", () => {
      expect(typeof new ConnectionsApi(config)["listFacebookPages"]).toBe("function");
    });
    it("exposes listPinterestBoards", () => {
      expect(typeof new ConnectionsApi(config)["listPinterestBoards"]).toBe("function");
    });
    it("exposes selectFacebookPage", () => {
      expect(typeof new ConnectionsApi(config)["selectFacebookPage"]).toBe("function");
    });
    it("exposes startOAuth", () => {
      expect(typeof new ConnectionsApi(config)["startOAuth"]).toBe("function");
    });
  });

  describe("MediaApi", () => {
    it("exposes deleteMedia", () => {
      expect(typeof new MediaApi(config)["deleteMedia"]).toBe("function");
    });
    it("exposes listMedia", () => {
      expect(typeof new MediaApi(config)["listMedia"]).toBe("function");
    });
    it("exposes uploadMedia", () => {
      expect(typeof new MediaApi(config)["uploadMedia"]).toBe("function");
    });
  });

  describe("PostsApi", () => {
    it("exposes cancelPost", () => {
      expect(typeof new PostsApi(config)["cancelPost"]).toBe("function");
    });
    it("exposes createPost", () => {
      expect(typeof new PostsApi(config)["createPost"]).toBe("function");
    });
    it("exposes deletePostDestination", () => {
      expect(typeof new PostsApi(config)["deletePostDestination"]).toBe("function");
    });
    it("exposes getPost", () => {
      expect(typeof new PostsApi(config)["getPost"]).toBe("function");
    });
    it("exposes listPosts", () => {
      expect(typeof new PostsApi(config)["listPosts"]).toBe("function");
    });
  });

  describe("InsightsApi", () => {
    it("exposes getPostInsights", () => {
      expect(typeof new InsightsApi(config)["getPostInsights"]).toBe("function");
    });
    it("exposes getPostInsightsTimeline", () => {
      expect(typeof new InsightsApi(config)["getPostInsightsTimeline"]).toBe("function");
    });
  });

  describe("CommentsApi", () => {
    it("exposes createComment", () => {
      expect(typeof new CommentsApi(config)["createComment"]).toBe("function");
    });
    it("exposes deleteComment", () => {
      expect(typeof new CommentsApi(config)["deleteComment"]).toBe("function");
    });
    it("exposes listComments", () => {
      expect(typeof new CommentsApi(config)["listComments"]).toBe("function");
    });
  });

  describe("EngagementApi", () => {
    it("exposes bookmark", () => {
      expect(typeof new EngagementApi(config)["bookmark"]).toBe("function");
    });
    it("exposes like", () => {
      expect(typeof new EngagementApi(config)["like"]).toBe("function");
    });
    it("exposes listRetweeters", () => {
      expect(typeof new EngagementApi(config)["listRetweeters"]).toBe("function");
    });
    it("exposes quote", () => {
      expect(typeof new EngagementApi(config)["quote"]).toBe("function");
    });
    it("exposes removeBookmark", () => {
      expect(typeof new EngagementApi(config)["removeBookmark"]).toBe("function");
    });
    it("exposes retweet", () => {
      expect(typeof new EngagementApi(config)["retweet"]).toBe("function");
    });
    it("exposes undoRetweet", () => {
      expect(typeof new EngagementApi(config)["undoRetweet"]).toBe("function");
    });
    it("exposes unlike", () => {
      expect(typeof new EngagementApi(config)["unlike"]).toBe("function");
    });
  });

  describe("WebhooksApi", () => {
    it("exposes createWebhook", () => {
      expect(typeof new WebhooksApi(config)["createWebhook"]).toBe("function");
    });
    it("exposes deleteWebhook", () => {
      expect(typeof new WebhooksApi(config)["deleteWebhook"]).toBe("function");
    });
    it("exposes getWebhook", () => {
      expect(typeof new WebhooksApi(config)["getWebhook"]).toBe("function");
    });
    it("exposes listWebhookDeliveries", () => {
      expect(typeof new WebhooksApi(config)["listWebhookDeliveries"]).toBe("function");
    });
    it("exposes listWebhookEventTypes", () => {
      expect(typeof new WebhooksApi(config)["listWebhookEventTypes"]).toBe("function");
    });
    it("exposes listWebhooks", () => {
      expect(typeof new WebhooksApi(config)["listWebhooks"]).toBe("function");
    });
    it("exposes rotateWebhookSecret", () => {
      expect(typeof new WebhooksApi(config)["rotateWebhookSecret"]).toBe("function");
    });
    it("exposes testWebhook", () => {
      expect(typeof new WebhooksApi(config)["testWebhook"]).toBe("function");
    });
    it("exposes updateWebhook", () => {
      expect(typeof new WebhooksApi(config)["updateWebhook"]).toBe("function");
    });
  });

});
