/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type GetAnalytics200Response,
    GetAnalytics200ResponseFromJSON,
    GetAnalytics200ResponseToJSON,
} from '../models/GetAnalytics200Response.js';
import {
    type GetAnalyticsTimeline200Response,
    GetAnalyticsTimeline200ResponseFromJSON,
    GetAnalyticsTimeline200ResponseToJSON,
} from '../models/GetAnalyticsTimeline200Response.js';

export interface GetAnalyticsRequest {
    /**
     * Internal post id or platform-native post id. Native ids require accountId.
     */
    post: string;
    /**
     * Required for platform-native post ids; disambiguates internal posts with several destinations.
     */
    accountId?: string;
    /**
     * Internal destinations only. Mutually narrows with accountId.
     */
    destinationId?: string;
}

export interface GetAnalyticsTimelineRequest {
    /**
     * Internal post id or platform-native post id. Native ids require accountId.
     */
    post: string;
    /**
     * Required for platform-native post ids; disambiguates internal posts with several destinations.
     */
    accountId?: string;
    /**
     * Internal destinations only. Mutually narrows with accountId.
     */
    destinationId?: string;
    /**
     * Inclusive start date (YYYY-MM-DD).
     */
    from?: string;
    /**
     * Inclusive end date (YYYY-MM-DD).
     */
    to?: string;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAnalytics without sending the request
     */
    async getAnalyticsRequestOpts(requestParameters: GetAnalyticsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['post'] == null) {
            throw new runtime.RequiredError(
                'post',
                'Required parameter "post" was null or undefined when calling getAnalytics().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['post'] != null) {
            queryParameters['post'] = requestParameters['post'];
        }

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['destinationId'] != null) {
            queryParameters['destinationId'] = requestParameters['destinationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/analytics`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Normalized metrics collected automatically for a post published through Onepostly or a platform-native post id. Posts younger than 30 days refresh about hourly, older subjects about weekly. Native post ids sync on first read; each subject carries fetchedAt. If it looks stale on an older subject, read again in a few minutes.
     * Get analytics
     */
    async getAnalyticsRaw(requestParameters: GetAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAnalytics200Response>> {
        const requestOptions = await this.getAnalyticsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalytics200ResponseFromJSON(jsonValue));
    }

    /**
     * Normalized metrics collected automatically for a post published through Onepostly or a platform-native post id. Posts younger than 30 days refresh about hourly, older subjects about weekly. Native post ids sync on first read; each subject carries fetchedAt. If it looks stale on an older subject, read again in a few minutes.
     * Get analytics
     */
    async getAnalytics(requestParameters: GetAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAnalytics200Response> {
        const response = await this.getAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAnalyticsTimeline without sending the request
     */
    async getAnalyticsTimelineRequestOpts(requestParameters: GetAnalyticsTimelineRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['post'] == null) {
            throw new runtime.RequiredError(
                'post',
                'Required parameter "post" was null or undefined when calling getAnalyticsTimeline().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['post'] != null) {
            queryParameters['post'] = requestParameters['post'];
        }

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['destinationId'] != null) {
            queryParameters['destinationId'] = requestParameters['destinationId'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = requestParameters['from'];
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = requestParameters['to'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/analytics/timeline`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Daily cumulative metrics per subject, captured automatically by the Onepostly pipeline. Range defaults to the last 366 days.
     * Get daily analytics timeline
     */
    async getAnalyticsTimelineRaw(requestParameters: GetAnalyticsTimelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAnalyticsTimeline200Response>> {
        const requestOptions = await this.getAnalyticsTimelineRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticsTimeline200ResponseFromJSON(jsonValue));
    }

    /**
     * Daily cumulative metrics per subject, captured automatically by the Onepostly pipeline. Range defaults to the last 366 days.
     * Get daily analytics timeline
     */
    async getAnalyticsTimeline(requestParameters: GetAnalyticsTimelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAnalyticsTimeline200Response> {
        const response = await this.getAnalyticsTimelineRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
