/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type Bookmark201Response,
    Bookmark201ResponseFromJSON,
    Bookmark201ResponseToJSON,
} from '../models/Bookmark201Response.js';
import {
    type DestinationIdBody,
    DestinationIdBodyFromJSON,
    DestinationIdBodyToJSON,
} from '../models/DestinationIdBody.js';
import {
    type Like201Response,
    Like201ResponseFromJSON,
    Like201ResponseToJSON,
} from '../models/Like201Response.js';
import {
    type ListRetweeters200Response,
    ListRetweeters200ResponseFromJSON,
    ListRetweeters200ResponseToJSON,
} from '../models/ListRetweeters200Response.js';
import {
    type Quote201Response,
    Quote201ResponseFromJSON,
    Quote201ResponseToJSON,
} from '../models/Quote201Response.js';
import {
    type QuoteBody,
    QuoteBodyFromJSON,
    QuoteBodyToJSON,
} from '../models/QuoteBody.js';
import {
    type Retweet201Response,
    Retweet201ResponseFromJSON,
    Retweet201ResponseToJSON,
} from '../models/Retweet201Response.js';

export interface BookmarkRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    destinationIdBody: DestinationIdBody;
}

export interface LikeRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    destinationIdBody: DestinationIdBody;
}

export interface ListRetweetersRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    destinationId?: string;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    cursor?: string;
}

export interface QuoteRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    quoteBody: QuoteBody;
}

export interface RemoveBookmarkRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    destinationId: string;
}

export interface RetweetRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    destinationIdBody: DestinationIdBody;
}

export interface UndoRetweetRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    destinationId: string;
}

export interface UnlikeRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    destinationId: string;
}

/**
 * 
 */
export class EngagementApi extends runtime.BaseAPI {

    /**
     * Creates request options for bookmark without sending the request
     */
    async bookmarkRequestOpts(requestParameters: BookmarkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bookmark().'
            );
        }

        if (requestParameters['destinationIdBody'] == null) {
            throw new runtime.RequiredError(
                'destinationIdBody',
                'Required parameter "destinationIdBody" was null or undefined when calling bookmark().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/bookmarks`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DestinationIdBodyToJSON(requestParameters['destinationIdBody']),
        };
    }

    /**
     * Bookmark
     */
    async bookmarkRaw(requestParameters: BookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark201Response>> {
        const requestOptions = await this.bookmarkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Bookmark201ResponseFromJSON(jsonValue));
    }

    /**
     * Bookmark
     */
    async bookmark(requestParameters: BookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark201Response> {
        const response = await this.bookmarkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for like without sending the request
     */
    async likeRequestOpts(requestParameters: LikeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling like().'
            );
        }

        if (requestParameters['destinationIdBody'] == null) {
            throw new runtime.RequiredError(
                'destinationIdBody',
                'Required parameter "destinationIdBody" was null or undefined when calling like().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/likes`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DestinationIdBodyToJSON(requestParameters['destinationIdBody']),
        };
    }

    /**
     * Like
     */
    async likeRaw(requestParameters: LikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Like201Response>> {
        const requestOptions = await this.likeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Like201ResponseFromJSON(jsonValue));
    }

    /**
     * Like
     */
    async like(requestParameters: LikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Like201Response> {
        const response = await this.likeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRetweeters without sending the request
     */
    async listRetweetersRequestOpts(requestParameters: ListRetweetersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listRetweeters().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['destinationId'] != null) {
            queryParameters['destinationId'] = requestParameters['destinationId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/retweets`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List retweeters
     */
    async listRetweetersRaw(requestParameters: ListRetweetersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRetweeters200Response>> {
        const requestOptions = await this.listRetweetersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRetweeters200ResponseFromJSON(jsonValue));
    }

    /**
     * List retweeters
     */
    async listRetweeters(requestParameters: ListRetweetersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRetweeters200Response> {
        const response = await this.listRetweetersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for quote without sending the request
     */
    async quoteRequestOpts(requestParameters: QuoteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling quote().'
            );
        }

        if (requestParameters['quoteBody'] == null) {
            throw new runtime.RequiredError(
                'quoteBody',
                'Required parameter "quoteBody" was null or undefined when calling quote().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/quotes`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuoteBodyToJSON(requestParameters['quoteBody']),
        };
    }

    /**
     * Quote tweet
     */
    async quoteRaw(requestParameters: QuoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Quote201Response>> {
        const requestOptions = await this.quoteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Quote201ResponseFromJSON(jsonValue));
    }

    /**
     * Quote tweet
     */
    async quote(requestParameters: QuoteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Quote201Response> {
        const response = await this.quoteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeBookmark without sending the request
     */
    async removeBookmarkRequestOpts(requestParameters: RemoveBookmarkRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeBookmark().'
            );
        }

        if (requestParameters['destinationId'] == null) {
            throw new runtime.RequiredError(
                'destinationId',
                'Required parameter "destinationId" was null or undefined when calling removeBookmark().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['destinationId'] != null) {
            queryParameters['destinationId'] = requestParameters['destinationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/bookmarks`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove bookmark
     */
    async removeBookmarkRaw(requestParameters: RemoveBookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bookmark201Response>> {
        const requestOptions = await this.removeBookmarkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Bookmark201ResponseFromJSON(jsonValue));
    }

    /**
     * Remove bookmark
     */
    async removeBookmark(requestParameters: RemoveBookmarkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bookmark201Response> {
        const response = await this.removeBookmarkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for retweet without sending the request
     */
    async retweetRequestOpts(requestParameters: RetweetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retweet().'
            );
        }

        if (requestParameters['destinationIdBody'] == null) {
            throw new runtime.RequiredError(
                'destinationIdBody',
                'Required parameter "destinationIdBody" was null or undefined when calling retweet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/retweets`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DestinationIdBodyToJSON(requestParameters['destinationIdBody']),
        };
    }

    /**
     * Retweet
     */
    async retweetRaw(requestParameters: RetweetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Retweet201Response>> {
        const requestOptions = await this.retweetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Retweet201ResponseFromJSON(jsonValue));
    }

    /**
     * Retweet
     */
    async retweet(requestParameters: RetweetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Retweet201Response> {
        const response = await this.retweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for undoRetweet without sending the request
     */
    async undoRetweetRequestOpts(requestParameters: UndoRetweetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling undoRetweet().'
            );
        }

        if (requestParameters['destinationId'] == null) {
            throw new runtime.RequiredError(
                'destinationId',
                'Required parameter "destinationId" was null or undefined when calling undoRetweet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['destinationId'] != null) {
            queryParameters['destinationId'] = requestParameters['destinationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/retweets`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Undo retweet
     */
    async undoRetweetRaw(requestParameters: UndoRetweetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Retweet201Response>> {
        const requestOptions = await this.undoRetweetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Retweet201ResponseFromJSON(jsonValue));
    }

    /**
     * Undo retweet
     */
    async undoRetweet(requestParameters: UndoRetweetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Retweet201Response> {
        const response = await this.undoRetweetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unlike without sending the request
     */
    async unlikeRequestOpts(requestParameters: UnlikeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unlike().'
            );
        }

        if (requestParameters['destinationId'] == null) {
            throw new runtime.RequiredError(
                'destinationId',
                'Required parameter "destinationId" was null or undefined when calling unlike().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['destinationId'] != null) {
            queryParameters['destinationId'] = requestParameters['destinationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/posts/{id}/likes`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Unlike
     */
    async unlikeRaw(requestParameters: UnlikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Like201Response>> {
        const requestOptions = await this.unlikeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Like201ResponseFromJSON(jsonValue));
    }

    /**
     * Unlike
     */
    async unlike(requestParameters: UnlikeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Like201Response> {
        const response = await this.unlikeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
