/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type CreateInboxConversation201Response,
    CreateInboxConversation201ResponseFromJSON,
    CreateInboxConversation201ResponseToJSON,
} from '../models/CreateInboxConversation201Response.js';
import {
    type CreateInboxConversationBody,
    CreateInboxConversationBodyFromJSON,
    CreateInboxConversationBodyToJSON,
} from '../models/CreateInboxConversationBody.js';
import {
    type ListInboxConversations200Response,
    ListInboxConversations200ResponseFromJSON,
    ListInboxConversations200ResponseToJSON,
} from '../models/ListInboxConversations200Response.js';
import {
    type ListInboxMessages200Response,
    ListInboxMessages200ResponseFromJSON,
    ListInboxMessages200ResponseToJSON,
} from '../models/ListInboxMessages200Response.js';
import {
    type SendInboxMessage201Response,
    SendInboxMessage201ResponseFromJSON,
    SendInboxMessage201ResponseToJSON,
} from '../models/SendInboxMessage201Response.js';
import {
    type SendInboxMessageBody,
    SendInboxMessageBodyFromJSON,
    SendInboxMessageBodyToJSON,
} from '../models/SendInboxMessageBody.js';

export interface CreateInboxConversationRequest {
    /**
     * 
     */
    createInboxConversationBody: CreateInboxConversationBody;
}

export interface ListInboxConversationsRequest {
    /**
     * Connection id.
     */
    accountId: string;
    /**
     * 
     */
    limit?: number;
    /**
     * Pagination cursor from the previous response.
     */
    cursor?: string;
}

export interface ListInboxMessagesRequest {
    /**
     * 
     */
    convoId: string;
    /**
     * Connection id.
     */
    accountId: string;
    /**
     * 
     */
    limit?: number;
    /**
     * Pagination cursor from the previous response.
     */
    cursor?: string;
}

export interface SendInboxMessageRequest {
    /**
     * 
     */
    sendInboxMessageBody: SendInboxMessageBody;
}

/**
 * 
 */
export class InboxApi extends runtime.BaseAPI {

    /**
     * Creates request options for createInboxConversation without sending the request
     */
    async createInboxConversationRequestOpts(requestParameters: CreateInboxConversationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createInboxConversationBody'] == null) {
            throw new runtime.RequiredError(
                'createInboxConversationBody',
                'Required parameter "createInboxConversationBody" was null or undefined when calling createInboxConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/inbox/conversations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInboxConversationBodyToJSON(requestParameters['createInboxConversationBody']),
        };
    }

    /**
     * Starts a 1-1 conversation with a recipient. Accepts a platform-native user identifier (username, user id, handle, or DID). Currently supported: Bluesky, Instagram, Facebook.
     * Create inbox conversation
     */
    async createInboxConversationRaw(requestParameters: CreateInboxConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateInboxConversation201Response>> {
        const requestOptions = await this.createInboxConversationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateInboxConversation201ResponseFromJSON(jsonValue));
    }

    /**
     * Starts a 1-1 conversation with a recipient. Accepts a platform-native user identifier (username, user id, handle, or DID). Currently supported: Bluesky, Instagram, Facebook.
     * Create inbox conversation
     */
    async createInboxConversation(requestParameters: CreateInboxConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateInboxConversation201Response> {
        const response = await this.createInboxConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listInboxConversations without sending the request
     */
    async listInboxConversationsRequestOpts(requestParameters: ListInboxConversationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling listInboxConversations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/inbox/conversations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Inbox conversations for the connected account. Currently supported: Bluesky, Instagram, Facebook.
     * List inbox conversations
     */
    async listInboxConversationsRaw(requestParameters: ListInboxConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListInboxConversations200Response>> {
        const requestOptions = await this.listInboxConversationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListInboxConversations200ResponseFromJSON(jsonValue));
    }

    /**
     * Inbox conversations for the connected account. Currently supported: Bluesky, Instagram, Facebook.
     * List inbox conversations
     */
    async listInboxConversations(requestParameters: ListInboxConversationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListInboxConversations200Response> {
        const response = await this.listInboxConversationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listInboxMessages without sending the request
     */
    async listInboxMessagesRequestOpts(requestParameters: ListInboxMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['convoId'] == null) {
            throw new runtime.RequiredError(
                'convoId',
                'Required parameter "convoId" was null or undefined when calling listInboxMessages().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling listInboxMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['accountId'] != null) {
            queryParameters['accountId'] = requestParameters['accountId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/inbox/conversations/{convoId}/messages`;
        urlPath = urlPath.replace('{convoId}', encodeURIComponent(String(requestParameters['convoId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Messages of one conversation, newest first. Currently supported: Bluesky, Instagram, Facebook.
     * List inbox messages
     */
    async listInboxMessagesRaw(requestParameters: ListInboxMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListInboxMessages200Response>> {
        const requestOptions = await this.listInboxMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListInboxMessages200ResponseFromJSON(jsonValue));
    }

    /**
     * Messages of one conversation, newest first. Currently supported: Bluesky, Instagram, Facebook.
     * List inbox messages
     */
    async listInboxMessages(requestParameters: ListInboxMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListInboxMessages200Response> {
        const response = await this.listInboxMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendInboxMessage without sending the request
     */
    async sendInboxMessageRequestOpts(requestParameters: SendInboxMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendInboxMessageBody'] == null) {
            throw new runtime.RequiredError(
                'sendInboxMessageBody',
                'Required parameter "sendInboxMessageBody" was null or undefined when calling sendInboxMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/inbox/messages`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendInboxMessageBodyToJSON(requestParameters['sendInboxMessageBody']),
        };
    }

    /**
     * Sends a text message to a conversation. Currently supported: Bluesky, Instagram, Facebook. Instagram and Facebook also support quickReplies, button templates, and generic carousels.
     * Send inbox message
     */
    async sendInboxMessageRaw(requestParameters: SendInboxMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendInboxMessage201Response>> {
        const requestOptions = await this.sendInboxMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendInboxMessage201ResponseFromJSON(jsonValue));
    }

    /**
     * Sends a text message to a conversation. Currently supported: Bluesky, Instagram, Facebook. Instagram and Facebook also support quickReplies, button templates, and generic carousels.
     * Send inbox message
     */
    async sendInboxMessage(requestParameters: SendInboxMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendInboxMessage201Response> {
        const response = await this.sendInboxMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
