/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js';
import {
    type ListMedia200Response,
    ListMedia200ResponseFromJSON,
    ListMedia200ResponseToJSON,
} from '../models/ListMedia200Response.js';
import {
    type PresignMediaBody,
    PresignMediaBodyFromJSON,
    PresignMediaBodyToJSON,
} from '../models/PresignMediaBody.js';
import {
    type PresignedUpload,
    PresignedUploadFromJSON,
    PresignedUploadToJSON,
} from '../models/PresignedUpload.js';

export interface DeleteMediaRequest {
    /**
     * 
     */
    id: string;
}

export interface GetMediaPresignedUrlRequest {
    /**
     * 
     */
    presignMediaBody: PresignMediaBody;
}

export interface ListMediaRequest {
    /**
     * Page size (default varies by endpoint).
     */
    limit?: number;
    /**
     * Offset for list endpoints.
     */
    offset?: number | null;
}

/**
 * 
 */
export class MediaApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteMedia without sending the request
     */
    async deleteMediaRequestOpts(requestParameters: DeleteMediaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/media/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete media
     */
    async deleteMediaRaw(requestParameters: DeleteMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete media
     */
    async deleteMedia(requestParameters: DeleteMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteMediaRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getMediaPresignedUrl without sending the request
     */
    async getMediaPresignedUrlRequestOpts(requestParameters: GetMediaPresignedUrlRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['presignMediaBody'] == null) {
            throw new runtime.RequiredError(
                'presignMediaBody',
                'Required parameter "presignMediaBody" was null or undefined when calling getMediaPresignedUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/media/presign`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PresignMediaBodyToJSON(requestParameters['presignMediaBody']),
        };
    }

    /**
     * Get a presigned upload URL
     */
    async getMediaPresignedUrlRaw(requestParameters: GetMediaPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresignedUpload>> {
        const requestOptions = await this.getMediaPresignedUrlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresignedUploadFromJSON(jsonValue));
    }

    /**
     * Get a presigned upload URL
     */
    async getMediaPresignedUrl(requestParameters: GetMediaPresignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresignedUpload> {
        const response = await this.getMediaPresignedUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMedia without sending the request
     */
    async listMediaRequestOpts(requestParameters: ListMediaRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyHeader authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("ApiKeyBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/media`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List media
     */
    async listMediaRaw(requestParameters: ListMediaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMedia200Response>> {
        const requestOptions = await this.listMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListMedia200ResponseFromJSON(jsonValue));
    }

    /**
     * List media
     */
    async listMedia(requestParameters: ListMediaRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMedia200Response> {
        const response = await this.listMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
