/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Actor
 */
export interface Actor {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    username?: string | null;
    /**
     * 
     */
    displayName?: string | null;
    /**
     * 
     */
    avatarUrl?: string | null;
}

/**
 * Check if a given object implements the Actor interface.
 */
export function instanceOfActor(value: object): value is Actor {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ActorFromJSON(json: any): Actor {
    return ActorFromJSONTyped(json, false);
}

export function ActorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Actor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'] === undefined ? undefined : json['username'] === null ? null : json['username'],
        'displayName': json['displayName'] === undefined ? undefined : json['displayName'] === null ? null : json['displayName'],
        'avatarUrl': json['avatarUrl'] === undefined ? undefined : json['avatarUrl'] === null ? null : json['avatarUrl'],
    };
}

export function ActorToJSON(json: any): Actor {
    return ActorToJSONTyped(json, false);
}

export function ActorToJSONTyped(value?: Actor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'displayName': value['displayName'],
        'avatarUrl': value['avatarUrl'],
    };
}

