/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    username?: string | null;
    /**
     * 
     */
    likeCount?: number | null;
    /**
     * 
     */
    timestamp?: string | null;
    /**
     * 
     */
    parentId?: string | null;
    /**
     * 
     */
    replies?: Array<Comment>;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': json['text'],
        'username': json['username'] === undefined ? undefined : json['username'] === null ? null : json['username'],
        'likeCount': json['likeCount'] === undefined ? undefined : json['likeCount'] === null ? null : json['likeCount'],
        'timestamp': json['timestamp'] === undefined ? undefined : json['timestamp'] === null ? null : json['timestamp'],
        'parentId': json['parentId'] === undefined ? undefined : json['parentId'] === null ? null : json['parentId'],
        'replies': json['replies'] == null ? undefined : ((json['replies'] as Array<any>).map(CommentFromJSON)),
    };
}

export function CommentToJSON(json: any): Comment {
    return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(value?: Comment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'username': value['username'],
        'likeCount': value['likeCount'],
        'timestamp': value['timestamp'],
        'parentId': value['parentId'],
        'replies': value['replies'] == null ? undefined : ((value['replies'] as Array<any>).map(CommentToJSON)),
    };
}

