/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ConnectBlueskyRequest
 */
export interface ConnectBlueskyRequest {
    /**
     * Handle, email, or DID (e.g. alice.bsky.social).
     */
    identifier: string;
    /**
     * App Password (xxxx-xxxx-xxxx-xxxx).
     */
    appPassword: string;
    /**
     * Existing connection id to re-authorize without consuming a plan slot.
     */
    reconnectId?: string;
}

/**
 * Check if a given object implements the ConnectBlueskyRequest interface.
 */
export function instanceOfConnectBlueskyRequest(value: object): value is ConnectBlueskyRequest {
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('appPassword' in value) || value['appPassword'] === undefined) return false;
    return true;
}

export function ConnectBlueskyRequestFromJSON(json: any): ConnectBlueskyRequest {
    return ConnectBlueskyRequestFromJSONTyped(json, false);
}

export function ConnectBlueskyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectBlueskyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'appPassword': json['appPassword'],
        'reconnectId': json['reconnectId'] == null ? undefined : json['reconnectId'],
    };
}

export function ConnectBlueskyRequestToJSON(json: any): ConnectBlueskyRequest {
    return ConnectBlueskyRequestToJSONTyped(json, false);
}

export function ConnectBlueskyRequestToJSONTyped(value?: ConnectBlueskyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'appPassword': value['appPassword'],
        'reconnectId': value['reconnectId'],
    };
}

