/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface Connection
 */
export interface Connection {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    displayName?: string;
    /**
     * 
     */
    handle?: string;
    /**
     * 
     */
    avatarUrl?: string | null;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    authHealth: ConnectionAuthHealthEnum;
    /**
     * 
     */
    createdAt?: Date;
    /**
     * 
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const ConnectionAuthHealthEnum = {
    Healthy: 'healthy',
    ActionRequired: 'action_required',
} as const;
export type ConnectionAuthHealthEnum = typeof ConnectionAuthHealthEnum[keyof typeof ConnectionAuthHealthEnum];


/**
 * Check if a given object implements the Connection interface.
 */
export function instanceOfConnection(value: object): value is Connection {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('authHealth' in value) || value['authHealth'] === undefined) return false;
    return true;
}

export function ConnectionFromJSON(json: any): Connection {
    return ConnectionFromJSONTyped(json, false);
}

export function ConnectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Connection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'platform': json['platform'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'handle': json['handle'] == null ? undefined : json['handle'],
        'avatarUrl': json['avatarUrl'] === undefined ? undefined : json['avatarUrl'] === null ? null : json['avatarUrl'],
        'status': json['status'],
        'authHealth': json['authHealth'],
        'createdAt': json['createdAt'] == null ? undefined : (parseDateTime(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (parseDateTime(json['updatedAt'])),
    };
}

export function ConnectionToJSON(json: any): Connection {
    return ConnectionToJSONTyped(json, false);
}

export function ConnectionToJSONTyped(value?: Connection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'platform': value['platform'],
        'displayName': value['displayName'],
        'handle': value['handle'],
        'avatarUrl': value['avatarUrl'],
        'status': value['status'],
        'authHealth': value['authHealth'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

