/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface ConnectionProfile
 */
export interface ConnectionProfile {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    tone: ConnectionProfileToneEnum;
    /**
     * Live connections filed under this profile.
     */
    connectionCount: number;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const ConnectionProfileToneEnum = {
    Neutral: 'neutral',
    Blue: 'blue',
    Green: 'green',
    Moss: 'moss',
    Purple: 'purple',
    Teal: 'teal',
    Amber: 'amber',
    Yellow: 'yellow',
    Orange: 'orange',
    Red: 'red',
} as const;
export type ConnectionProfileToneEnum = typeof ConnectionProfileToneEnum[keyof typeof ConnectionProfileToneEnum];


/**
 * Check if a given object implements the ConnectionProfile interface.
 */
export function instanceOfConnectionProfile(value: object): value is ConnectionProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tone' in value) || value['tone'] === undefined) return false;
    if (!('connectionCount' in value) || value['connectionCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ConnectionProfileFromJSON(json: any): ConnectionProfile {
    return ConnectionProfileFromJSONTyped(json, false);
}

export function ConnectionProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'tone': json['tone'],
        'connectionCount': json['connectionCount'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function ConnectionProfileToJSON(json: any): ConnectionProfile {
    return ConnectionProfileToJSONTyped(json, false);
}

export function ConnectionProfileToJSONTyped(value?: ConnectionProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tone': value['tone'],
        'connectionCount': value['connectionCount'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

