/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreatePrivateReplyRequest
 */
export interface CreatePrivateReplyRequest {
    /**
     * Internal post id or platform-native post id. Native ids require accountId. Omit only when destinationId is passed on its own.
     */
    post?: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * Globally unique destination id. Resolves on its own; post and accountId are optional alongside it.
     */
    destinationId?: string;
    /**
     * Platform-native comment id.
     */
    commentId: string;
    /**
     * 
     */
    text: string;
}

/**
 * Check if a given object implements the CreatePrivateReplyRequest interface.
 */
export function instanceOfCreatePrivateReplyRequest(value: object): value is CreatePrivateReplyRequest {
    if (!('commentId' in value) || value['commentId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CreatePrivateReplyRequestFromJSON(json: any): CreatePrivateReplyRequest {
    return CreatePrivateReplyRequestFromJSONTyped(json, false);
}

export function CreatePrivateReplyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrivateReplyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'post': json['post'] == null ? undefined : json['post'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'destinationId': json['destinationId'] == null ? undefined : json['destinationId'],
        'commentId': json['commentId'],
        'text': json['text'],
    };
}

export function CreatePrivateReplyRequestToJSON(json: any): CreatePrivateReplyRequest {
    return CreatePrivateReplyRequestToJSONTyped(json, false);
}

export function CreatePrivateReplyRequestToJSONTyped(value?: CreatePrivateReplyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': value['post'],
        'accountId': value['accountId'],
        'destinationId': value['destinationId'],
        'commentId': value['commentId'],
        'text': value['text'],
    };
}

