/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateWebhookBody
 */
export interface CreateWebhookBody {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    url: string;
    /**
     * 
     */
    secret?: string;
    /**
     * 
     */
    events: Array<string>;
    /**
     * 
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the CreateWebhookBody interface.
 */
export function instanceOfCreateWebhookBody(value: object): value is CreateWebhookBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function CreateWebhookBodyFromJSON(json: any): CreateWebhookBody {
    return CreateWebhookBodyFromJSONTyped(json, false);
}

export function CreateWebhookBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookBody {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'events': json['events'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function CreateWebhookBodyToJSON(json: any): CreateWebhookBody {
    return CreateWebhookBodyToJSONTyped(json, false);
}

export function CreateWebhookBodyToJSONTyped(value?: CreateWebhookBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'secret': value['secret'],
        'events': value['events'],
        'enabled': value['enabled'],
    };
}

