/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreateAutomation201ResponseRule } from './CreateAutomation201ResponseRule.js';
import {
    CreateAutomation201ResponseRuleFromJSON,
    CreateAutomation201ResponseRuleFromJSONTyped,
    CreateAutomation201ResponseRuleToJSON,
    CreateAutomation201ResponseRuleToJSONTyped,
} from './CreateAutomation201ResponseRule.js';

/**
 * 
 * @export
 * @interface CreateAutomation201Response
 */
export interface CreateAutomation201Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    rule: CreateAutomation201ResponseRule;
}

/**
 * Check if a given object implements the CreateAutomation201Response interface.
 */
export function instanceOfCreateAutomation201Response(value: object): value is CreateAutomation201Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('rule' in value) || value['rule'] === undefined) return false;
    return true;
}

export function CreateAutomation201ResponseFromJSON(json: any): CreateAutomation201Response {
    return CreateAutomation201ResponseFromJSONTyped(json, false);
}

export function CreateAutomation201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutomation201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'rule': CreateAutomation201ResponseRuleFromJSON(json['rule']),
    };
}

export function CreateAutomation201ResponseToJSON(json: any): CreateAutomation201Response {
    return CreateAutomation201ResponseToJSONTyped(json, false);
}

export function CreateAutomation201ResponseToJSONTyped(value?: CreateAutomation201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'rule': CreateAutomation201ResponseRuleToJSON(value['rule']),
    };
}

