/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreatePrivateReply201ResponseReplyReply
 */
export interface CreatePrivateReply201ResponseReplyReply {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    timestamp: string;
}

/**
 * Check if a given object implements the CreatePrivateReply201ResponseReplyReply interface.
 */
export function instanceOfCreatePrivateReply201ResponseReplyReply(value: object): value is CreatePrivateReply201ResponseReplyReply {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function CreatePrivateReply201ResponseReplyReplyFromJSON(json: any): CreatePrivateReply201ResponseReplyReply {
    return CreatePrivateReply201ResponseReplyReplyFromJSONTyped(json, false);
}

export function CreatePrivateReply201ResponseReplyReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrivateReply201ResponseReplyReply {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': json['text'],
        'timestamp': json['timestamp'],
    };
}

export function CreatePrivateReply201ResponseReplyReplyToJSON(json: any): CreatePrivateReply201ResponseReplyReply {
    return CreatePrivateReply201ResponseReplyReplyToJSONTyped(json, false);
}

export function CreatePrivateReply201ResponseReplyReplyToJSONTyped(value?: CreatePrivateReply201ResponseReplyReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'timestamp': value['timestamp'],
    };
}

