/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateAutomationBody
 */
export interface CreateAutomationBody {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    kind: CreateAutomationBodyKindEnum;
    /**
     * Label for the rule.
     */
    name: string;
    /**
     * Case-insensitive substring matches. At least one keyword is required.
     */
    keywords: Array<string>;
    /**
     * Skip the rule when the comment or message contains any of these.
     */
    excludeKeywords?: Array<string>;
    /**
     * 
     */
    dmMessage: string;
}


/**
 * @export
 */
export const CreateAutomationBodyKindEnum = {
    CommentToDm: 'comment_to_dm',
    StoryReply: 'story_reply',
    WelcomeDm: 'welcome_dm',
} as const;
export type CreateAutomationBodyKindEnum = typeof CreateAutomationBodyKindEnum[keyof typeof CreateAutomationBodyKindEnum];


/**
 * Check if a given object implements the CreateAutomationBody interface.
 */
export function instanceOfCreateAutomationBody(value: object): value is CreateAutomationBody {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    if (!('dmMessage' in value) || value['dmMessage'] === undefined) return false;
    return true;
}

export function CreateAutomationBodyFromJSON(json: any): CreateAutomationBody {
    return CreateAutomationBodyFromJSONTyped(json, false);
}

export function CreateAutomationBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutomationBody {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'kind': json['kind'],
        'name': json['name'],
        'keywords': json['keywords'],
        'excludeKeywords': json['excludeKeywords'] == null ? undefined : json['excludeKeywords'],
        'dmMessage': json['dmMessage'],
    };
}

export function CreateAutomationBodyToJSON(json: any): CreateAutomationBody {
    return CreateAutomationBodyToJSONTyped(json, false);
}

export function CreateAutomationBodyToJSONTyped(value?: CreateAutomationBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'kind': value['kind'],
        'name': value['name'],
        'keywords': value['keywords'],
        'excludeKeywords': value['excludeKeywords'],
        'dmMessage': value['dmMessage'],
    };
}

