/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreateWebhook201ResponseWebhook } from './CreateWebhook201ResponseWebhook.js';
import {
    CreateWebhook201ResponseWebhookFromJSON,
    CreateWebhook201ResponseWebhookFromJSONTyped,
    CreateWebhook201ResponseWebhookToJSON,
    CreateWebhook201ResponseWebhookToJSONTyped,
} from './CreateWebhook201ResponseWebhook.js';

/**
 * 
 * @export
 * @interface CreateWebhook201Response
 */
export interface CreateWebhook201Response {
    /**
     * 
     */
    webhook: CreateWebhook201ResponseWebhook;
}

/**
 * Check if a given object implements the CreateWebhook201Response interface.
 */
export function instanceOfCreateWebhook201Response(value: object): value is CreateWebhook201Response {
    if (!('webhook' in value) || value['webhook'] === undefined) return false;
    return true;
}

export function CreateWebhook201ResponseFromJSON(json: any): CreateWebhook201Response {
    return CreateWebhook201ResponseFromJSONTyped(json, false);
}

export function CreateWebhook201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhook201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'webhook': CreateWebhook201ResponseWebhookFromJSON(json['webhook']),
    };
}

export function CreateWebhook201ResponseToJSON(json: any): CreateWebhook201Response {
    return CreateWebhook201ResponseToJSONTyped(json, false);
}

export function CreateWebhook201ResponseToJSONTyped(value?: CreateWebhook201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhook': CreateWebhook201ResponseWebhookToJSON(value['webhook']),
    };
}

