/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreatePostBodyDestinationsInnerCarouselCardsInner
 */
export interface CreatePostBodyDestinationsInnerCarouselCardsInner {
    /**
     * 
     */
    link: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    description?: string;
}

/**
 * Check if a given object implements the CreatePostBodyDestinationsInnerCarouselCardsInner interface.
 */
export function instanceOfCreatePostBodyDestinationsInnerCarouselCardsInner(value: object): value is CreatePostBodyDestinationsInnerCarouselCardsInner {
    if (!('link' in value) || value['link'] === undefined) return false;
    return true;
}

export function CreatePostBodyDestinationsInnerCarouselCardsInnerFromJSON(json: any): CreatePostBodyDestinationsInnerCarouselCardsInner {
    return CreatePostBodyDestinationsInnerCarouselCardsInnerFromJSONTyped(json, false);
}

export function CreatePostBodyDestinationsInnerCarouselCardsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostBodyDestinationsInnerCarouselCardsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreatePostBodyDestinationsInnerCarouselCardsInnerToJSON(json: any): CreatePostBodyDestinationsInnerCarouselCardsInner {
    return CreatePostBodyDestinationsInnerCarouselCardsInnerToJSONTyped(json, false);
}

export function CreatePostBodyDestinationsInnerCarouselCardsInnerToJSONTyped(value?: CreatePostBodyDestinationsInnerCarouselCardsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': value['link'],
        'name': value['name'],
        'description': value['description'],
    };
}

