/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateProfileRequest
 */
export interface CreateProfileRequest {
    /**
     * Workspace-unique profile name.
     */
    name: string;
}

/**
 * Check if a given object implements the CreateProfileRequest interface.
 */
export function instanceOfCreateProfileRequest(value: object): value is CreateProfileRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProfileRequestFromJSON(json: any): CreateProfileRequest {
    return CreateProfileRequestFromJSONTyped(json, false);
}

export function CreateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateProfileRequestToJSON(json: any): CreateProfileRequest {
    return CreateProfileRequestToJSONTyped(json, false);
}

export function CreateProfileRequestToJSONTyped(value?: CreateProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

