/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateAutomation201ResponseRule
 */
export interface CreateAutomation201ResponseRule {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    kind: CreateAutomation201ResponseRuleKindEnum;
    /**
     * Case-insensitive substring triggers. Empty means every comment or message matches.
     */
    keywords: Array<string>;
    /**
     * Skip the rule when the comment or message contains any of these.
     */
    excludeKeywords: Array<string>;
    /**
     * 
     */
    dmMessage: string;
    /**
     * 
     */
    enabled: boolean;
}


/**
 * @export
 */
export const CreateAutomation201ResponseRuleKindEnum = {
    CommentToDm: 'comment_to_dm',
    StoryReply: 'story_reply',
    WelcomeDm: 'welcome_dm',
} as const;
export type CreateAutomation201ResponseRuleKindEnum = typeof CreateAutomation201ResponseRuleKindEnum[keyof typeof CreateAutomation201ResponseRuleKindEnum];


/**
 * Check if a given object implements the CreateAutomation201ResponseRule interface.
 */
export function instanceOfCreateAutomation201ResponseRule(value: object): value is CreateAutomation201ResponseRule {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    if (!('excludeKeywords' in value) || value['excludeKeywords'] === undefined) return false;
    if (!('dmMessage' in value) || value['dmMessage'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function CreateAutomation201ResponseRuleFromJSON(json: any): CreateAutomation201ResponseRule {
    return CreateAutomation201ResponseRuleFromJSONTyped(json, false);
}

export function CreateAutomation201ResponseRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutomation201ResponseRule {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'kind': json['kind'],
        'keywords': json['keywords'],
        'excludeKeywords': json['excludeKeywords'],
        'dmMessage': json['dmMessage'],
        'enabled': json['enabled'],
    };
}

export function CreateAutomation201ResponseRuleToJSON(json: any): CreateAutomation201ResponseRule {
    return CreateAutomation201ResponseRuleToJSONTyped(json, false);
}

export function CreateAutomation201ResponseRuleToJSONTyped(value?: CreateAutomation201ResponseRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'kind': value['kind'],
        'keywords': value['keywords'],
        'excludeKeywords': value['excludeKeywords'],
        'dmMessage': value['dmMessage'],
        'enabled': value['enabled'],
    };
}

