/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreatePostBodyDestinationsInner
 */
export interface CreatePostBodyDestinationsInner {
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    text?: string;
    /**
     * 
     */
    quoteTweetId?: string;
    /**
     * 
     */
    privacyStatus?: CreatePostBodyDestinationsInnerPrivacyStatusEnum;
    /**
     * 
     */
    privacyLevel?: CreatePostBodyDestinationsInnerPrivacyLevelEnum;
    /**
     * 
     */
    disableComment?: boolean;
    /**
     * 
     */
    disableDuet?: boolean;
    /**
     * 
     */
    disableStitch?: boolean;
    /**
     * 
     */
    brandOrganicToggle?: boolean;
    /**
     * 
     */
    brandContentToggle?: boolean;
    /**
     * 
     */
    description?: string;
    /**
     * Pinterest only. Required for Pinterest destinations.
     */
    boardId?: string;
    /**
     * 
     */
    link?: string;
    /**
     * 
     */
    title?: string;
    /**
     * 
     */
    subreddit?: string;
    /**
     * 
     */
    flairId?: string;
    /**
     * 
     */
    flairText?: string;
    /**
     * 
     */
    nsfw?: boolean;
    /**
     * 
     */
    spoiler?: boolean;
    /**
     * 
     */
    thumbnailUrl?: string;
}


/**
 * @export
 */
export const CreatePostBodyDestinationsInnerPrivacyStatusEnum = {
    Public: 'public',
    Private: 'private',
    Unlisted: 'unlisted',
} as const;
export type CreatePostBodyDestinationsInnerPrivacyStatusEnum = typeof CreatePostBodyDestinationsInnerPrivacyStatusEnum[keyof typeof CreatePostBodyDestinationsInnerPrivacyStatusEnum];

/**
 * @export
 */
export const CreatePostBodyDestinationsInnerPrivacyLevelEnum = {
    PublicToEveryone: 'PUBLIC_TO_EVERYONE',
    MutualFollowFriends: 'MUTUAL_FOLLOW_FRIENDS',
    FollowerOfCreator: 'FOLLOWER_OF_CREATOR',
    SelfOnly: 'SELF_ONLY',
} as const;
export type CreatePostBodyDestinationsInnerPrivacyLevelEnum = typeof CreatePostBodyDestinationsInnerPrivacyLevelEnum[keyof typeof CreatePostBodyDestinationsInnerPrivacyLevelEnum];


/**
 * Check if a given object implements the CreatePostBodyDestinationsInner interface.
 */
export function instanceOfCreatePostBodyDestinationsInner(value: object): value is CreatePostBodyDestinationsInner {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    return true;
}

export function CreatePostBodyDestinationsInnerFromJSON(json: any): CreatePostBodyDestinationsInner {
    return CreatePostBodyDestinationsInnerFromJSONTyped(json, false);
}

export function CreatePostBodyDestinationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostBodyDestinationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
        'text': json['text'] == null ? undefined : json['text'],
        'quoteTweetId': json['quoteTweetId'] == null ? undefined : json['quoteTweetId'],
        'privacyStatus': json['privacyStatus'] == null ? undefined : json['privacyStatus'],
        'privacyLevel': json['privacyLevel'] == null ? undefined : json['privacyLevel'],
        'disableComment': json['disableComment'] == null ? undefined : json['disableComment'],
        'disableDuet': json['disableDuet'] == null ? undefined : json['disableDuet'],
        'disableStitch': json['disableStitch'] == null ? undefined : json['disableStitch'],
        'brandOrganicToggle': json['brandOrganicToggle'] == null ? undefined : json['brandOrganicToggle'],
        'brandContentToggle': json['brandContentToggle'] == null ? undefined : json['brandContentToggle'],
        'description': json['description'] == null ? undefined : json['description'],
        'boardId': json['boardId'] == null ? undefined : json['boardId'],
        'link': json['link'] == null ? undefined : json['link'],
        'title': json['title'] == null ? undefined : json['title'],
        'subreddit': json['subreddit'] == null ? undefined : json['subreddit'],
        'flairId': json['flairId'] == null ? undefined : json['flairId'],
        'flairText': json['flairText'] == null ? undefined : json['flairText'],
        'nsfw': json['nsfw'] == null ? undefined : json['nsfw'],
        'spoiler': json['spoiler'] == null ? undefined : json['spoiler'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
    };
}

export function CreatePostBodyDestinationsInnerToJSON(json: any): CreatePostBodyDestinationsInner {
    return CreatePostBodyDestinationsInnerToJSONTyped(json, false);
}

export function CreatePostBodyDestinationsInnerToJSONTyped(value?: CreatePostBodyDestinationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectionId': value['connectionId'],
        'text': value['text'],
        'quoteTweetId': value['quoteTweetId'],
        'privacyStatus': value['privacyStatus'],
        'privacyLevel': value['privacyLevel'],
        'disableComment': value['disableComment'],
        'disableDuet': value['disableDuet'],
        'disableStitch': value['disableStitch'],
        'brandOrganicToggle': value['brandOrganicToggle'],
        'brandContentToggle': value['brandContentToggle'],
        'description': value['description'],
        'boardId': value['boardId'],
        'link': value['link'],
        'title': value['title'],
        'subreddit': value['subreddit'],
        'flairId': value['flairId'],
        'flairText': value['flairText'],
        'nsfw': value['nsfw'],
        'spoiler': value['spoiler'],
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

