/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { ListPinterestBoards200ResponseBoardsInner } from './ListPinterestBoards200ResponseBoardsInner.js';
import {
    ListPinterestBoards200ResponseBoardsInnerFromJSON,
    ListPinterestBoards200ResponseBoardsInnerFromJSONTyped,
    ListPinterestBoards200ResponseBoardsInnerToJSON,
    ListPinterestBoards200ResponseBoardsInnerToJSONTyped,
} from './ListPinterestBoards200ResponseBoardsInner.js';

/**
 * 
 * @export
 * @interface CreatePinterestBoard201Response
 */
export interface CreatePinterestBoard201Response {
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    platform: CreatePinterestBoard201ResponsePlatformEnum;
    /**
     * 
     */
    board: ListPinterestBoards200ResponseBoardsInner;
    /**
     * 
     */
    sandbox: boolean;
    /**
     * 
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CreatePinterestBoard201ResponsePlatformEnum = {
    Pinterest: 'pinterest',
} as const;
export type CreatePinterestBoard201ResponsePlatformEnum = typeof CreatePinterestBoard201ResponsePlatformEnum[keyof typeof CreatePinterestBoard201ResponsePlatformEnum];


/**
 * Check if a given object implements the CreatePinterestBoard201Response interface.
 */
export function instanceOfCreatePinterestBoard201Response(value: object): value is CreatePinterestBoard201Response {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (value['platform'] !== 'pinterest') return false;
    
    if (!('board' in value) || value['board'] === undefined) return false;
    if (!('sandbox' in value) || value['sandbox'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreatePinterestBoard201ResponseFromJSON(json: any): CreatePinterestBoard201Response {
    return CreatePinterestBoard201ResponseFromJSONTyped(json, false);
}

export function CreatePinterestBoard201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePinterestBoard201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
        'platform': json['platform'],
        'board': ListPinterestBoards200ResponseBoardsInnerFromJSON(json['board']),
        'sandbox': json['sandbox'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function CreatePinterestBoard201ResponseToJSON(json: any): CreatePinterestBoard201Response {
    return CreatePinterestBoard201ResponseToJSONTyped(json, false);
}

export function CreatePinterestBoard201ResponseToJSONTyped(value?: CreatePinterestBoard201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectionId': value['connectionId'],
        'platform': value['platform'],
        'board': ListPinterestBoards200ResponseBoardsInnerToJSON(value['board']),
        'sandbox': value['sandbox'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

