/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateCommentBody
 */
export interface CreateCommentBody {
    /**
     * Internal post id or platform-native post id. Native ids require accountId. Omit only when destinationId is passed on its own.
     */
    post?: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * Globally unique destination id. Resolves on its own; post and accountId are optional alongside it.
     */
    destinationId?: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    parentCommentId?: string;
}

/**
 * Check if a given object implements the CreateCommentBody interface.
 */
export function instanceOfCreateCommentBody(value: object): value is CreateCommentBody {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function CreateCommentBodyFromJSON(json: any): CreateCommentBody {
    return CreateCommentBodyFromJSONTyped(json, false);
}

export function CreateCommentBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentBody {
    if (json == null) {
        return json;
    }
    return {
        
        'post': json['post'] == null ? undefined : json['post'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'destinationId': json['destinationId'] == null ? undefined : json['destinationId'],
        'text': json['text'],
        'parentCommentId': json['parentCommentId'] == null ? undefined : json['parentCommentId'],
    };
}

export function CreateCommentBodyToJSON(json: any): CreateCommentBody {
    return CreateCommentBodyToJSONTyped(json, false);
}

export function CreateCommentBodyToJSONTyped(value?: CreateCommentBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': value['post'],
        'accountId': value['accountId'],
        'destinationId': value['destinationId'],
        'text': value['text'],
        'parentCommentId': value['parentCommentId'],
    };
}

