/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ConnectionProfile } from './ConnectionProfile.js';
import {
    ConnectionProfileFromJSON,
    ConnectionProfileFromJSONTyped,
    ConnectionProfileToJSON,
    ConnectionProfileToJSONTyped,
} from './ConnectionProfile.js';

/**
 * 
 * @export
 * @interface CreateProfile201Response
 */
export interface CreateProfile201Response {
    /**
     * 
     */
    profile: ConnectionProfile;
}

/**
 * Check if a given object implements the CreateProfile201Response interface.
 */
export function instanceOfCreateProfile201Response(value: object): value is CreateProfile201Response {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function CreateProfile201ResponseFromJSON(json: any): CreateProfile201Response {
    return CreateProfile201ResponseFromJSONTyped(json, false);
}

export function CreateProfile201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProfile201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': ConnectionProfileFromJSON(json['profile']),
    };
}

export function CreateProfile201ResponseToJSON(json: any): CreateProfile201Response {
    return CreateProfile201ResponseToJSONTyped(json, false);
}

export function CreateProfile201ResponseToJSONTyped(value?: CreateProfile201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': ConnectionProfileToJSON(value['profile']),
    };
}

