/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreatePostBodyDestinationsInner } from './CreatePostBodyDestinationsInner.js';
import {
    CreatePostBodyDestinationsInnerFromJSON,
    CreatePostBodyDestinationsInnerFromJSONTyped,
    CreatePostBodyDestinationsInnerToJSON,
    CreatePostBodyDestinationsInnerToJSONTyped,
} from './CreatePostBodyDestinationsInner.js';
import type { MediaKind } from './MediaKind.js';
import {
    MediaKindFromJSON,
    MediaKindFromJSONTyped,
    MediaKindToJSON,
    MediaKindToJSONTyped,
} from './MediaKind.js';

/**
 * 
 * @export
 * @interface CreatePostBody
 */
export interface CreatePostBody {
    /**
     * 
     */
    text?: string;
    /**
     * 
     */
    thread?: Array<string>;
    /**
     * 
     */
    mediaUrls?: Array<string>;
    /**
     * 
     */
    mediaKind: MediaKind;
    /**
     * 
     */
    scheduledFor?: string;
    /**
     * 
     */
    timezone?: string;
    /**
     * 
     */
    destinations: Array<CreatePostBodyDestinationsInner>;
}



/**
 * Check if a given object implements the CreatePostBody interface.
 */
export function instanceOfCreatePostBody(value: object): value is CreatePostBody {
    if (!('mediaKind' in value) || value['mediaKind'] === undefined) return false;
    if (!('destinations' in value) || value['destinations'] === undefined) return false;
    return true;
}

export function CreatePostBodyFromJSON(json: any): CreatePostBody {
    return CreatePostBodyFromJSONTyped(json, false);
}

export function CreatePostBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostBody {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'thread': json['thread'] == null ? undefined : json['thread'],
        'mediaUrls': json['mediaUrls'] == null ? undefined : json['mediaUrls'],
        'mediaKind': MediaKindFromJSON(json['mediaKind']),
        'scheduledFor': json['scheduledFor'] == null ? undefined : json['scheduledFor'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'destinations': ((json['destinations'] as Array<any>).map(CreatePostBodyDestinationsInnerFromJSON)),
    };
}

export function CreatePostBodyToJSON(json: any): CreatePostBody {
    return CreatePostBodyToJSONTyped(json, false);
}

export function CreatePostBodyToJSONTyped(value?: CreatePostBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'thread': value['thread'],
        'mediaUrls': value['mediaUrls'],
        'mediaKind': MediaKindToJSON(value['mediaKind']),
        'scheduledFor': value['scheduledFor'],
        'timezone': value['timezone'],
        'destinations': ((value['destinations'] as Array<any>).map(CreatePostBodyDestinationsInnerToJSON)),
    };
}

