/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CreatePrivateReply201ResponseReplyReply } from './CreatePrivateReply201ResponseReplyReply.js';
import {
    CreatePrivateReply201ResponseReplyReplyFromJSON,
    CreatePrivateReply201ResponseReplyReplyFromJSONTyped,
    CreatePrivateReply201ResponseReplyReplyToJSON,
    CreatePrivateReply201ResponseReplyReplyToJSONTyped,
} from './CreatePrivateReply201ResponseReplyReply.js';

/**
 * 
 * @export
 * @interface CreatePrivateReply201ResponseReply
 */
export interface CreatePrivateReply201ResponseReply {
    /**
     * 
     */
    postId: string;
    /**
     * 
     */
    destinationId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    commentId: string;
    /**
     * 
     */
    reply: CreatePrivateReply201ResponseReplyReply;
}

/**
 * Check if a given object implements the CreatePrivateReply201ResponseReply interface.
 */
export function instanceOfCreatePrivateReply201ResponseReply(value: object): value is CreatePrivateReply201ResponseReply {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('commentId' in value) || value['commentId'] === undefined) return false;
    if (!('reply' in value) || value['reply'] === undefined) return false;
    return true;
}

export function CreatePrivateReply201ResponseReplyFromJSON(json: any): CreatePrivateReply201ResponseReply {
    return CreatePrivateReply201ResponseReplyFromJSONTyped(json, false);
}

export function CreatePrivateReply201ResponseReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrivateReply201ResponseReply {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'destinationId': json['destinationId'],
        'platform': json['platform'],
        'commentId': json['commentId'],
        'reply': CreatePrivateReply201ResponseReplyReplyFromJSON(json['reply']),
    };
}

export function CreatePrivateReply201ResponseReplyToJSON(json: any): CreatePrivateReply201ResponseReply {
    return CreatePrivateReply201ResponseReplyToJSONTyped(json, false);
}

export function CreatePrivateReply201ResponseReplyToJSONTyped(value?: CreatePrivateReply201ResponseReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'destinationId': value['destinationId'],
        'platform': value['platform'],
        'commentId': value['commentId'],
        'reply': CreatePrivateReply201ResponseReplyReplyToJSON(value['reply']),
    };
}

