/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DeleteComment200Response
 */
export interface DeleteComment200Response {
    /**
     * 
     */
    deleted?: any | null;
}

/**
 * Check if a given object implements the DeleteComment200Response interface.
 */
export function instanceOfDeleteComment200Response(value: object): value is DeleteComment200Response {
    return true;
}

export function DeleteComment200ResponseFromJSON(json: any): DeleteComment200Response {
    return DeleteComment200ResponseFromJSONTyped(json, false);
}

export function DeleteComment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteComment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'] === undefined ? undefined : json['deleted'] === null ? null : json['deleted'],
    };
}

export function DeleteComment200ResponseToJSON(json: any): DeleteComment200Response {
    return DeleteComment200ResponseToJSONTyped(json, false);
}

export function DeleteComment200ResponseToJSONTyped(value?: DeleteComment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

