/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DestinationIdBody
 */
export interface DestinationIdBody {
    /**
     * 
     */
    destinationId: string;
}

/**
 * Check if a given object implements the DestinationIdBody interface.
 */
export function instanceOfDestinationIdBody(value: object): value is DestinationIdBody {
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    return true;
}

export function DestinationIdBodyFromJSON(json: any): DestinationIdBody {
    return DestinationIdBodyFromJSONTyped(json, false);
}

export function DestinationIdBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationIdBody {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationId': json['destinationId'],
    };
}

export function DestinationIdBodyToJSON(json: any): DestinationIdBody {
    return DestinationIdBodyToJSONTyped(json, false);
}

export function DestinationIdBodyToJSONTyped(value?: DestinationIdBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationId': value['destinationId'],
    };
}

