/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface EngagementTargetBody
 */
export interface EngagementTargetBody {
    /**
     * Internal post id or platform-native post id. Native ids require accountId.
     */
    post: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * 
     */
    destinationId?: string;
}

/**
 * Check if a given object implements the EngagementTargetBody interface.
 */
export function instanceOfEngagementTargetBody(value: object): value is EngagementTargetBody {
    if (!('post' in value) || value['post'] === undefined) return false;
    return true;
}

export function EngagementTargetBodyFromJSON(json: any): EngagementTargetBody {
    return EngagementTargetBodyFromJSONTyped(json, false);
}

export function EngagementTargetBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EngagementTargetBody {
    if (json == null) {
        return json;
    }
    return {
        
        'post': json['post'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'destinationId': json['destinationId'] == null ? undefined : json['destinationId'],
    };
}

export function EngagementTargetBodyToJSON(json: any): EngagementTargetBody {
    return EngagementTargetBodyToJSONTyped(json, false);
}

export function EngagementTargetBodyToJSONTyped(value?: EngagementTargetBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': value['post'],
        'accountId': value['accountId'],
        'destinationId': value['destinationId'],
    };
}

