/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ExternalPost
 */
export interface ExternalPost {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    externalPostId: string;
    /**
     * 
     */
    externalUrl: string | null;
    /**
     * 
     */
    mediaKind: string;
    /**
     * 
     */
    publishedAt: string | null;
    /**
     * 
     */
    syncedAt: string;
    /**
     * 
     */
    analyticsStatus: string;
}

/**
 * Check if a given object implements the ExternalPost interface.
 */
export function instanceOfExternalPost(value: object): value is ExternalPost {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('externalPostId' in value) || value['externalPostId'] === undefined) return false;
    if (!('externalUrl' in value) || value['externalUrl'] === undefined) return false;
    if (!('mediaKind' in value) || value['mediaKind'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    if (!('syncedAt' in value) || value['syncedAt'] === undefined) return false;
    if (!('analyticsStatus' in value) || value['analyticsStatus'] === undefined) return false;
    return true;
}

export function ExternalPostFromJSON(json: any): ExternalPost {
    return ExternalPostFromJSONTyped(json, false);
}

export function ExternalPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalPost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'accountId': json['accountId'],
        'platform': json['platform'],
        'externalPostId': json['externalPostId'],
        'externalUrl': json['externalUrl'],
        'mediaKind': json['mediaKind'],
        'publishedAt': json['publishedAt'],
        'syncedAt': json['syncedAt'],
        'analyticsStatus': json['analyticsStatus'],
    };
}

export function ExternalPostToJSON(json: any): ExternalPost {
    return ExternalPostToJSONTyped(json, false);
}

export function ExternalPostToJSONTyped(value?: ExternalPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'accountId': value['accountId'],
        'platform': value['platform'],
        'externalPostId': value['externalPostId'],
        'externalUrl': value['externalUrl'],
        'mediaKind': value['mediaKind'],
        'publishedAt': value['publishedAt'],
        'syncedAt': value['syncedAt'],
        'analyticsStatus': value['analyticsStatus'],
    };
}

