/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NormalizedMetrics } from './NormalizedMetrics.js';
import {
    NormalizedMetricsFromJSON,
    NormalizedMetricsFromJSONTyped,
    NormalizedMetricsToJSON,
    NormalizedMetricsToJSONTyped,
} from './NormalizedMetrics.js';

/**
 * 
 * @export
 * @interface GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner
 */
export interface GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner {
    /**
     * 
     */
    day: string;
    /**
     * 
     */
    metrics?: NormalizedMetrics;
    /**
     * 
     */
    delta?: NormalizedMetrics;
}

/**
 * Check if a given object implements the GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner interface.
 */
export function instanceOfGetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner(value: object): value is GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner {
    if (!('day' in value) || value['day'] === undefined) return false;
    return true;
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerFromJSON(json: any): GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner {
    return GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerFromJSONTyped(json, false);
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'],
        'metrics': json['metrics'] == null ? undefined : NormalizedMetricsFromJSON(json['metrics']),
        'delta': json['delta'] == null ? undefined : NormalizedMetricsFromJSON(json['delta']),
    };
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerToJSON(json: any): GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner {
    return GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerToJSONTyped(json, false);
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerToJSONTyped(value?: GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'metrics': NormalizedMetricsToJSON(value['metrics']),
        'delta': NormalizedMetricsToJSON(value['delta']),
    };
}

