/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetAnalytics200ResponseAnalyticsSubjectsInnerError } from './GetAnalytics200ResponseAnalyticsSubjectsInnerError.js';
import {
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorFromJSON,
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorFromJSONTyped,
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorToJSON,
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorToJSONTyped,
} from './GetAnalytics200ResponseAnalyticsSubjectsInnerError.js';
import type { NormalizedMetrics } from './NormalizedMetrics.js';
import {
    NormalizedMetricsFromJSON,
    NormalizedMetricsFromJSONTyped,
    NormalizedMetricsToJSON,
    NormalizedMetricsToJSONTyped,
} from './NormalizedMetrics.js';

/**
 * 
 * @export
 * @interface GetAnalytics200ResponseAnalyticsSubjectsInner
 */
export interface GetAnalytics200ResponseAnalyticsSubjectsInner {
    /**
     * 
     */
    scope: GetAnalytics200ResponseAnalyticsSubjectsInnerScopeEnum;
    /**
     * 
     */
    subjectId: string;
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    externalPostId: string | null;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    metrics?: NormalizedMetrics;
    /**
     * 
     */
    fetchedAt?: string | null;
    /**
     * 
     */
    expiresAt?: string | null;
    /**
     * 
     */
    error: GetAnalytics200ResponseAnalyticsSubjectsInnerError | null;
}


/**
 * @export
 */
export const GetAnalytics200ResponseAnalyticsSubjectsInnerScopeEnum = {
    Destination: 'destination',
    External: 'external',
} as const;
export type GetAnalytics200ResponseAnalyticsSubjectsInnerScopeEnum = typeof GetAnalytics200ResponseAnalyticsSubjectsInnerScopeEnum[keyof typeof GetAnalytics200ResponseAnalyticsSubjectsInnerScopeEnum];


/**
 * Check if a given object implements the GetAnalytics200ResponseAnalyticsSubjectsInner interface.
 */
export function instanceOfGetAnalytics200ResponseAnalyticsSubjectsInner(value: object): value is GetAnalytics200ResponseAnalyticsSubjectsInner {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('externalPostId' in value) || value['externalPostId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetAnalytics200ResponseAnalyticsSubjectsInnerFromJSON(json: any): GetAnalytics200ResponseAnalyticsSubjectsInner {
    return GetAnalytics200ResponseAnalyticsSubjectsInnerFromJSONTyped(json, false);
}

export function GetAnalytics200ResponseAnalyticsSubjectsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalytics200ResponseAnalyticsSubjectsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
        'subjectId': json['subjectId'],
        'accountId': json['accountId'],
        'platform': json['platform'],
        'externalPostId': json['externalPostId'],
        'status': json['status'],
        'metrics': json['metrics'] == null ? undefined : NormalizedMetricsFromJSON(json['metrics']),
        'fetchedAt': json['fetchedAt'] === undefined ? undefined : json['fetchedAt'] === null ? null : json['fetchedAt'],
        'expiresAt': json['expiresAt'] === undefined ? undefined : json['expiresAt'] === null ? null : json['expiresAt'],
        'error': GetAnalytics200ResponseAnalyticsSubjectsInnerErrorFromJSON(json['error']),
    };
}

export function GetAnalytics200ResponseAnalyticsSubjectsInnerToJSON(json: any): GetAnalytics200ResponseAnalyticsSubjectsInner {
    return GetAnalytics200ResponseAnalyticsSubjectsInnerToJSONTyped(json, false);
}

export function GetAnalytics200ResponseAnalyticsSubjectsInnerToJSONTyped(value?: GetAnalytics200ResponseAnalyticsSubjectsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'subjectId': value['subjectId'],
        'accountId': value['accountId'],
        'platform': value['platform'],
        'externalPostId': value['externalPostId'],
        'status': value['status'],
        'metrics': NormalizedMetricsToJSON(value['metrics']),
        'fetchedAt': value['fetchedAt'],
        'expiresAt': value['expiresAt'],
        'error': GetAnalytics200ResponseAnalyticsSubjectsInnerErrorToJSON(value['error']),
    };
}

