/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetAnalytics200ResponseAnalytics } from './GetAnalytics200ResponseAnalytics.js';
import {
    GetAnalytics200ResponseAnalyticsFromJSON,
    GetAnalytics200ResponseAnalyticsFromJSONTyped,
    GetAnalytics200ResponseAnalyticsToJSON,
    GetAnalytics200ResponseAnalyticsToJSONTyped,
} from './GetAnalytics200ResponseAnalytics.js';

/**
 * 
 * @export
 * @interface GetAnalytics200Response
 */
export interface GetAnalytics200Response {
    /**
     * 
     */
    analytics: GetAnalytics200ResponseAnalytics;
}

/**
 * Check if a given object implements the GetAnalytics200Response interface.
 */
export function instanceOfGetAnalytics200Response(value: object): value is GetAnalytics200Response {
    if (!('analytics' in value) || value['analytics'] === undefined) return false;
    return true;
}

export function GetAnalytics200ResponseFromJSON(json: any): GetAnalytics200Response {
    return GetAnalytics200ResponseFromJSONTyped(json, false);
}

export function GetAnalytics200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalytics200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'analytics': GetAnalytics200ResponseAnalyticsFromJSON(json['analytics']),
    };
}

export function GetAnalytics200ResponseToJSON(json: any): GetAnalytics200Response {
    return GetAnalytics200ResponseToJSONTyped(json, false);
}

export function GetAnalytics200ResponseToJSONTyped(value?: GetAnalytics200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'analytics': GetAnalytics200ResponseAnalyticsToJSON(value['analytics']),
    };
}

