/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner } from './GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner.js';
import {
    GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerFromJSON,
    GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerFromJSONTyped,
    GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerToJSON,
    GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerToJSONTyped,
} from './GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner.js';

/**
 * 
 * @export
 * @interface GetAnalyticsTimeline200ResponseTimelineSubjectsInner
 */
export interface GetAnalyticsTimeline200ResponseTimelineSubjectsInner {
    /**
     * 
     */
    scope: GetAnalyticsTimeline200ResponseTimelineSubjectsInnerScopeEnum;
    /**
     * 
     */
    subjectId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    points?: Array<GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInner>;
}


/**
 * @export
 */
export const GetAnalyticsTimeline200ResponseTimelineSubjectsInnerScopeEnum = {
    Destination: 'destination',
    External: 'external',
} as const;
export type GetAnalyticsTimeline200ResponseTimelineSubjectsInnerScopeEnum = typeof GetAnalyticsTimeline200ResponseTimelineSubjectsInnerScopeEnum[keyof typeof GetAnalyticsTimeline200ResponseTimelineSubjectsInnerScopeEnum];


/**
 * Check if a given object implements the GetAnalyticsTimeline200ResponseTimelineSubjectsInner interface.
 */
export function instanceOfGetAnalyticsTimeline200ResponseTimelineSubjectsInner(value: object): value is GetAnalyticsTimeline200ResponseTimelineSubjectsInner {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerFromJSON(json: any): GetAnalyticsTimeline200ResponseTimelineSubjectsInner {
    return GetAnalyticsTimeline200ResponseTimelineSubjectsInnerFromJSONTyped(json, false);
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticsTimeline200ResponseTimelineSubjectsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
        'subjectId': json['subjectId'],
        'platform': json['platform'],
        'status': json['status'] == null ? undefined : json['status'],
        'points': json['points'] == null ? undefined : ((json['points'] as Array<any>).map(GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerFromJSON)),
    };
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerToJSON(json: any): GetAnalyticsTimeline200ResponseTimelineSubjectsInner {
    return GetAnalyticsTimeline200ResponseTimelineSubjectsInnerToJSONTyped(json, false);
}

export function GetAnalyticsTimeline200ResponseTimelineSubjectsInnerToJSONTyped(value?: GetAnalyticsTimeline200ResponseTimelineSubjectsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'subjectId': value['subjectId'],
        'platform': value['platform'],
        'status': value['status'],
        'points': value['points'] == null ? undefined : ((value['points'] as Array<any>).map(GetAnalyticsTimeline200ResponseTimelineSubjectsInnerPointsInnerToJSON)),
    };
}

