/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetBlueskySettings200Response
 */
export interface GetBlueskySettings200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: GetBlueskySettings200ResponsePlatformEnum;
    /**
     * 
     */
    defaultLangs: Array<string> | null;
    /**
     * 
     */
    fetchedAt: Date;
}


/**
 * @export
 */
export const GetBlueskySettings200ResponsePlatformEnum = {
    Bluesky: 'bluesky',
} as const;
export type GetBlueskySettings200ResponsePlatformEnum = typeof GetBlueskySettings200ResponsePlatformEnum[keyof typeof GetBlueskySettings200ResponsePlatformEnum];


/**
 * Check if a given object implements the GetBlueskySettings200Response interface.
 */
export function instanceOfGetBlueskySettings200Response(value: object): value is GetBlueskySettings200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (value['platform'] !== 'bluesky') return false;
    
    if (!('defaultLangs' in value) || value['defaultLangs'] === undefined) return false;
    if (!('fetchedAt' in value) || value['fetchedAt'] === undefined) return false;
    return true;
}

export function GetBlueskySettings200ResponseFromJSON(json: any): GetBlueskySettings200Response {
    return GetBlueskySettings200ResponseFromJSONTyped(json, false);
}

export function GetBlueskySettings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBlueskySettings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'platform': json['platform'],
        'defaultLangs': json['defaultLangs'] == null ? null : json['defaultLangs'],
        'fetchedAt': (json['fetchedAt'] == null ? json['fetchedAt'] : parseDateTime(json['fetchedAt'])),
    };
}

export function GetBlueskySettings200ResponseToJSON(json: any): GetBlueskySettings200Response {
    return GetBlueskySettings200ResponseToJSONTyped(json, false);
}

export function GetBlueskySettings200ResponseToJSONTyped(value?: GetBlueskySettings200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'platform': value['platform'],
        'defaultLangs': value['defaultLangs'],
        'fetchedAt': value['fetchedAt'] == null ? value['fetchedAt'] : serializeDateTime(value['fetchedAt']),
    };
}

