/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetConnectionStats200ResponseStats
 */
export interface GetConnectionStats200ResponseStats {
    /**
     * 
     */
    followerCount: number | null;
    /**
     * 
     */
    followingCount: number | null;
    /**
     * 
     */
    likesCount: number | null;
    /**
     * 
     */
    videoCount: number | null;
}

/**
 * Check if a given object implements the GetConnectionStats200ResponseStats interface.
 */
export function instanceOfGetConnectionStats200ResponseStats(value: object): value is GetConnectionStats200ResponseStats {
    if (!('followerCount' in value) || value['followerCount'] === undefined) return false;
    if (!('followingCount' in value) || value['followingCount'] === undefined) return false;
    if (!('likesCount' in value) || value['likesCount'] === undefined) return false;
    if (!('videoCount' in value) || value['videoCount'] === undefined) return false;
    return true;
}

export function GetConnectionStats200ResponseStatsFromJSON(json: any): GetConnectionStats200ResponseStats {
    return GetConnectionStats200ResponseStatsFromJSONTyped(json, false);
}

export function GetConnectionStats200ResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConnectionStats200ResponseStats {
    if (json == null) {
        return json;
    }
    return {
        
        'followerCount': json['followerCount'],
        'followingCount': json['followingCount'],
        'likesCount': json['likesCount'],
        'videoCount': json['videoCount'],
    };
}

export function GetConnectionStats200ResponseStatsToJSON(json: any): GetConnectionStats200ResponseStats {
    return GetConnectionStats200ResponseStatsToJSONTyped(json, false);
}

export function GetConnectionStats200ResponseStatsToJSONTyped(value?: GetConnectionStats200ResponseStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'followerCount': value['followerCount'],
        'followingCount': value['followingCount'],
        'likesCount': value['likesCount'],
        'videoCount': value['videoCount'],
    };
}

