/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetConnectionStats200Response
 */
export interface GetConnectionStats200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    stats?: { [key: string]: any | null; } | null;
    /**
     * 
     */
    fetchedAt: Date;
}

/**
 * Check if a given object implements the GetConnectionStats200Response interface.
 */
export function instanceOfGetConnectionStats200Response(value: object): value is GetConnectionStats200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fetchedAt' in value) || value['fetchedAt'] === undefined) return false;
    return true;
}

export function GetConnectionStats200ResponseFromJSON(json: any): GetConnectionStats200Response {
    return GetConnectionStats200ResponseFromJSONTyped(json, false);
}

export function GetConnectionStats200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConnectionStats200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'platform': json['platform'],
        'status': json['status'],
        'stats': json['stats'] === undefined ? undefined : json['stats'] === null ? null : json['stats'],
        'fetchedAt': (json['fetchedAt'] == null ? json['fetchedAt'] : parseDateTime(json['fetchedAt'])),
    };
}

export function GetConnectionStats200ResponseToJSON(json: any): GetConnectionStats200Response {
    return GetConnectionStats200ResponseToJSONTyped(json, false);
}

export function GetConnectionStats200ResponseToJSONTyped(value?: GetConnectionStats200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'platform': value['platform'],
        'status': value['status'],
        'stats': value['stats'],
        'fetchedAt': value['fetchedAt'] == null ? value['fetchedAt'] : serializeDateTime(value['fetchedAt']),
    };
}

