/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NormalizedMetrics } from './NormalizedMetrics.js';
import {
    NormalizedMetricsFromJSON,
    NormalizedMetricsFromJSONTyped,
    NormalizedMetricsToJSON,
    NormalizedMetricsToJSONTyped,
} from './NormalizedMetrics.js';

/**
 * 
 * @export
 * @interface GetPostInsights200ResponseInsightsDestinationsInner
 */
export interface GetPostInsights200ResponseInsightsDestinationsInner {
    /**
     * 
     */
    destinationId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    metrics?: NormalizedMetrics;
}

/**
 * Check if a given object implements the GetPostInsights200ResponseInsightsDestinationsInner interface.
 */
export function instanceOfGetPostInsights200ResponseInsightsDestinationsInner(value: object): value is GetPostInsights200ResponseInsightsDestinationsInner {
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function GetPostInsights200ResponseInsightsDestinationsInnerFromJSON(json: any): GetPostInsights200ResponseInsightsDestinationsInner {
    return GetPostInsights200ResponseInsightsDestinationsInnerFromJSONTyped(json, false);
}

export function GetPostInsights200ResponseInsightsDestinationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostInsights200ResponseInsightsDestinationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationId': json['destinationId'],
        'platform': json['platform'],
        'status': json['status'] == null ? undefined : json['status'],
        'metrics': json['metrics'] == null ? undefined : NormalizedMetricsFromJSON(json['metrics']),
    };
}

export function GetPostInsights200ResponseInsightsDestinationsInnerToJSON(json: any): GetPostInsights200ResponseInsightsDestinationsInner {
    return GetPostInsights200ResponseInsightsDestinationsInnerToJSONTyped(json, false);
}

export function GetPostInsights200ResponseInsightsDestinationsInnerToJSONTyped(value?: GetPostInsights200ResponseInsightsDestinationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationId': value['destinationId'],
        'platform': value['platform'],
        'status': value['status'],
        'metrics': NormalizedMetricsToJSON(value['metrics']),
    };
}

