/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { NormalizedMetrics } from './NormalizedMetrics.js';
import {
    NormalizedMetricsFromJSON,
    NormalizedMetricsFromJSONTyped,
    NormalizedMetricsToJSON,
    NormalizedMetricsToJSONTyped,
} from './NormalizedMetrics.js';

/**
 * 
 * @export
 * @interface GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner
 */
export interface GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner {
    /**
     * 
     */
    day: string;
    /**
     * 
     */
    metrics?: NormalizedMetrics;
    /**
     * 
     */
    delta?: NormalizedMetrics;
}

/**
 * Check if a given object implements the GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner interface.
 */
export function instanceOfGetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner(value: object): value is GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner {
    if (!('day' in value) || value['day'] === undefined) return false;
    return true;
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerFromJSON(json: any): GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner {
    return GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerFromJSONTyped(json, false);
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'],
        'metrics': json['metrics'] == null ? undefined : NormalizedMetricsFromJSON(json['metrics']),
        'delta': json['delta'] == null ? undefined : NormalizedMetricsFromJSON(json['delta']),
    };
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerToJSON(json: any): GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner {
    return GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerToJSONTyped(json, false);
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerToJSONTyped(value?: GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'metrics': NormalizedMetricsToJSON(value['metrics']),
        'delta': NormalizedMetricsToJSON(value['delta']),
    };
}

