/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner } from './GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner.js';
import {
    GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerFromJSON,
    GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerFromJSONTyped,
    GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerToJSON,
    GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerToJSONTyped,
} from './GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner.js';

/**
 * 
 * @export
 * @interface GetPostInsightsTimeline200ResponseTimelineDestinationsInner
 */
export interface GetPostInsightsTimeline200ResponseTimelineDestinationsInner {
    /**
     * 
     */
    destinationId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    points?: Array<GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInner>;
}

/**
 * Check if a given object implements the GetPostInsightsTimeline200ResponseTimelineDestinationsInner interface.
 */
export function instanceOfGetPostInsightsTimeline200ResponseTimelineDestinationsInner(value: object): value is GetPostInsightsTimeline200ResponseTimelineDestinationsInner {
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerFromJSON(json: any): GetPostInsightsTimeline200ResponseTimelineDestinationsInner {
    return GetPostInsightsTimeline200ResponseTimelineDestinationsInnerFromJSONTyped(json, false);
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostInsightsTimeline200ResponseTimelineDestinationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationId': json['destinationId'],
        'platform': json['platform'],
        'status': json['status'] == null ? undefined : json['status'],
        'points': json['points'] == null ? undefined : ((json['points'] as Array<any>).map(GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerFromJSON)),
    };
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerToJSON(json: any): GetPostInsightsTimeline200ResponseTimelineDestinationsInner {
    return GetPostInsightsTimeline200ResponseTimelineDestinationsInnerToJSONTyped(json, false);
}

export function GetPostInsightsTimeline200ResponseTimelineDestinationsInnerToJSONTyped(value?: GetPostInsightsTimeline200ResponseTimelineDestinationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationId': value['destinationId'],
        'platform': value['platform'],
        'status': value['status'],
        'points': value['points'] == null ? undefined : ((value['points'] as Array<any>).map(GetPostInsightsTimeline200ResponseTimelineDestinationsInnerPointsInnerToJSON)),
    };
}

