/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetPostInsights200ResponseInsightsDestinationsInner } from './GetPostInsights200ResponseInsightsDestinationsInner.js';
import {
    GetPostInsights200ResponseInsightsDestinationsInnerFromJSON,
    GetPostInsights200ResponseInsightsDestinationsInnerFromJSONTyped,
    GetPostInsights200ResponseInsightsDestinationsInnerToJSON,
    GetPostInsights200ResponseInsightsDestinationsInnerToJSONTyped,
} from './GetPostInsights200ResponseInsightsDestinationsInner.js';

/**
 * 
 * @export
 * @interface GetPostInsights200ResponseInsights
 */
export interface GetPostInsights200ResponseInsights {
    /**
     * 
     */
    postId: string;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    destinations?: Array<GetPostInsights200ResponseInsightsDestinationsInner>;
}

/**
 * Check if a given object implements the GetPostInsights200ResponseInsights interface.
 */
export function instanceOfGetPostInsights200ResponseInsights(value: object): value is GetPostInsights200ResponseInsights {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    return true;
}

export function GetPostInsights200ResponseInsightsFromJSON(json: any): GetPostInsights200ResponseInsights {
    return GetPostInsights200ResponseInsightsFromJSONTyped(json, false);
}

export function GetPostInsights200ResponseInsightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostInsights200ResponseInsights {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'status': json['status'] == null ? undefined : json['status'],
        'destinations': json['destinations'] == null ? undefined : ((json['destinations'] as Array<any>).map(GetPostInsights200ResponseInsightsDestinationsInnerFromJSON)),
    };
}

export function GetPostInsights200ResponseInsightsToJSON(json: any): GetPostInsights200ResponseInsights {
    return GetPostInsights200ResponseInsightsToJSONTyped(json, false);
}

export function GetPostInsights200ResponseInsightsToJSONTyped(value?: GetPostInsights200ResponseInsights | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'status': value['status'],
        'destinations': value['destinations'] == null ? undefined : ((value['destinations'] as Array<any>).map(GetPostInsights200ResponseInsightsDestinationsInnerToJSON)),
    };
}

