/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetPostInsightsTimeline200ResponseTimeline } from './GetPostInsightsTimeline200ResponseTimeline.js';
import {
    GetPostInsightsTimeline200ResponseTimelineFromJSON,
    GetPostInsightsTimeline200ResponseTimelineFromJSONTyped,
    GetPostInsightsTimeline200ResponseTimelineToJSON,
    GetPostInsightsTimeline200ResponseTimelineToJSONTyped,
} from './GetPostInsightsTimeline200ResponseTimeline.js';

/**
 * 
 * @export
 * @interface GetPostInsightsTimeline200Response
 */
export interface GetPostInsightsTimeline200Response {
    /**
     * 
     */
    timeline: GetPostInsightsTimeline200ResponseTimeline;
}

/**
 * Check if a given object implements the GetPostInsightsTimeline200Response interface.
 */
export function instanceOfGetPostInsightsTimeline200Response(value: object): value is GetPostInsightsTimeline200Response {
    if (!('timeline' in value) || value['timeline'] === undefined) return false;
    return true;
}

export function GetPostInsightsTimeline200ResponseFromJSON(json: any): GetPostInsightsTimeline200Response {
    return GetPostInsightsTimeline200ResponseFromJSONTyped(json, false);
}

export function GetPostInsightsTimeline200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPostInsightsTimeline200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'timeline': GetPostInsightsTimeline200ResponseTimelineFromJSON(json['timeline']),
    };
}

export function GetPostInsightsTimeline200ResponseToJSON(json: any): GetPostInsightsTimeline200Response {
    return GetPostInsightsTimeline200ResponseToJSONTyped(json, false);
}

export function GetPostInsightsTimeline200ResponseToJSONTyped(value?: GetPostInsightsTimeline200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeline': GetPostInsightsTimeline200ResponseTimelineToJSON(value['timeline']),
    };
}

