/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { GetTikTokCreatorInfo200ResponseCreatorInfo } from './GetTikTokCreatorInfo200ResponseCreatorInfo.js';
import {
    GetTikTokCreatorInfo200ResponseCreatorInfoFromJSON,
    GetTikTokCreatorInfo200ResponseCreatorInfoFromJSONTyped,
    GetTikTokCreatorInfo200ResponseCreatorInfoToJSON,
    GetTikTokCreatorInfo200ResponseCreatorInfoToJSONTyped,
} from './GetTikTokCreatorInfo200ResponseCreatorInfo.js';

/**
 * 
 * @export
 * @interface GetTikTokCreatorInfo200Response
 */
export interface GetTikTokCreatorInfo200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: GetTikTokCreatorInfo200ResponsePlatformEnum;
    /**
     * 
     */
    creatorInfo: GetTikTokCreatorInfo200ResponseCreatorInfo;
    /**
     * 
     */
    fetchedAt: Date;
}


/**
 * @export
 */
export const GetTikTokCreatorInfo200ResponsePlatformEnum = {
    Tiktok: 'tiktok',
} as const;
export type GetTikTokCreatorInfo200ResponsePlatformEnum = typeof GetTikTokCreatorInfo200ResponsePlatformEnum[keyof typeof GetTikTokCreatorInfo200ResponsePlatformEnum];


/**
 * Check if a given object implements the GetTikTokCreatorInfo200Response interface.
 */
export function instanceOfGetTikTokCreatorInfo200Response(value: object): value is GetTikTokCreatorInfo200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (value['platform'] !== 'tiktok') return false;
    
    if (!('creatorInfo' in value) || value['creatorInfo'] === undefined) return false;
    if (!('fetchedAt' in value) || value['fetchedAt'] === undefined) return false;
    return true;
}

export function GetTikTokCreatorInfo200ResponseFromJSON(json: any): GetTikTokCreatorInfo200Response {
    return GetTikTokCreatorInfo200ResponseFromJSONTyped(json, false);
}

export function GetTikTokCreatorInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTikTokCreatorInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'platform': json['platform'],
        'creatorInfo': GetTikTokCreatorInfo200ResponseCreatorInfoFromJSON(json['creatorInfo']),
        'fetchedAt': (json['fetchedAt'] == null ? json['fetchedAt'] : parseDateTime(json['fetchedAt'])),
    };
}

export function GetTikTokCreatorInfo200ResponseToJSON(json: any): GetTikTokCreatorInfo200Response {
    return GetTikTokCreatorInfo200ResponseToJSONTyped(json, false);
}

export function GetTikTokCreatorInfo200ResponseToJSONTyped(value?: GetTikTokCreatorInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'platform': value['platform'],
        'creatorInfo': GetTikTokCreatorInfo200ResponseCreatorInfoToJSON(value['creatorInfo']),
        'fetchedAt': value['fetchedAt'] == null ? value['fetchedAt'] : serializeDateTime(value['fetchedAt']),
    };
}

