/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetTikTokCreatorInfo200ResponseCreatorInfo
 */
export interface GetTikTokCreatorInfo200ResponseCreatorInfo {
    /**
     * 
     */
    creatorAvatarUrl: string | null;
    /**
     * 
     */
    creatorUsername: string | null;
    /**
     * 
     */
    creatorNickname: string | null;
    /**
     * 
     */
    privacyLevelOptions: Array<string>;
    /**
     * 
     */
    commentDisabled: boolean;
    /**
     * 
     */
    duetDisabled: boolean;
    /**
     * 
     */
    stitchDisabled: boolean;
    /**
     * 
     */
    maxVideoPostDurationSec: number | null;
}

/**
 * Check if a given object implements the GetTikTokCreatorInfo200ResponseCreatorInfo interface.
 */
export function instanceOfGetTikTokCreatorInfo200ResponseCreatorInfo(value: object): value is GetTikTokCreatorInfo200ResponseCreatorInfo {
    if (!('creatorAvatarUrl' in value) || value['creatorAvatarUrl'] === undefined) return false;
    if (!('creatorUsername' in value) || value['creatorUsername'] === undefined) return false;
    if (!('creatorNickname' in value) || value['creatorNickname'] === undefined) return false;
    if (!('privacyLevelOptions' in value) || value['privacyLevelOptions'] === undefined) return false;
    if (!('commentDisabled' in value) || value['commentDisabled'] === undefined) return false;
    if (!('duetDisabled' in value) || value['duetDisabled'] === undefined) return false;
    if (!('stitchDisabled' in value) || value['stitchDisabled'] === undefined) return false;
    if (!('maxVideoPostDurationSec' in value) || value['maxVideoPostDurationSec'] === undefined) return false;
    return true;
}

export function GetTikTokCreatorInfo200ResponseCreatorInfoFromJSON(json: any): GetTikTokCreatorInfo200ResponseCreatorInfo {
    return GetTikTokCreatorInfo200ResponseCreatorInfoFromJSONTyped(json, false);
}

export function GetTikTokCreatorInfo200ResponseCreatorInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTikTokCreatorInfo200ResponseCreatorInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'creatorAvatarUrl': json['creatorAvatarUrl'],
        'creatorUsername': json['creatorUsername'],
        'creatorNickname': json['creatorNickname'],
        'privacyLevelOptions': json['privacyLevelOptions'],
        'commentDisabled': json['commentDisabled'],
        'duetDisabled': json['duetDisabled'],
        'stitchDisabled': json['stitchDisabled'],
        'maxVideoPostDurationSec': json['maxVideoPostDurationSec'],
    };
}

export function GetTikTokCreatorInfo200ResponseCreatorInfoToJSON(json: any): GetTikTokCreatorInfo200ResponseCreatorInfo {
    return GetTikTokCreatorInfo200ResponseCreatorInfoToJSONTyped(json, false);
}

export function GetTikTokCreatorInfo200ResponseCreatorInfoToJSONTyped(value?: GetTikTokCreatorInfo200ResponseCreatorInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creatorAvatarUrl': value['creatorAvatarUrl'],
        'creatorUsername': value['creatorUsername'],
        'creatorNickname': value['creatorNickname'],
        'privacyLevelOptions': value['privacyLevelOptions'],
        'commentDisabled': value['commentDisabled'],
        'duetDisabled': value['duetDisabled'],
        'stitchDisabled': value['stitchDisabled'],
        'maxVideoPostDurationSec': value['maxVideoPostDurationSec'],
    };
}

