/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { GetWebhookDeliverySummary200ResponseEndpointsInner } from './GetWebhookDeliverySummary200ResponseEndpointsInner.js';
import {
    GetWebhookDeliverySummary200ResponseEndpointsInnerFromJSON,
    GetWebhookDeliverySummary200ResponseEndpointsInnerFromJSONTyped,
    GetWebhookDeliverySummary200ResponseEndpointsInnerToJSON,
    GetWebhookDeliverySummary200ResponseEndpointsInnerToJSONTyped,
} from './GetWebhookDeliverySummary200ResponseEndpointsInner.js';

/**
 * 
 * @export
 * @interface GetWebhookDeliverySummary200Response
 */
export interface GetWebhookDeliverySummary200Response {
    /**
     * 
     */
    rangeDays: number;
    /**
     * 
     */
    bucketCount: number;
    /**
     * 
     */
    endpoints: Array<GetWebhookDeliverySummary200ResponseEndpointsInner>;
}

/**
 * Check if a given object implements the GetWebhookDeliverySummary200Response interface.
 */
export function instanceOfGetWebhookDeliverySummary200Response(value: object): value is GetWebhookDeliverySummary200Response {
    if (!('rangeDays' in value) || value['rangeDays'] === undefined) return false;
    if (!('bucketCount' in value) || value['bucketCount'] === undefined) return false;
    if (!('endpoints' in value) || value['endpoints'] === undefined) return false;
    return true;
}

export function GetWebhookDeliverySummary200ResponseFromJSON(json: any): GetWebhookDeliverySummary200Response {
    return GetWebhookDeliverySummary200ResponseFromJSONTyped(json, false);
}

export function GetWebhookDeliverySummary200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebhookDeliverySummary200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'rangeDays': json['rangeDays'],
        'bucketCount': json['bucketCount'],
        'endpoints': ((json['endpoints'] as Array<any>).map(GetWebhookDeliverySummary200ResponseEndpointsInnerFromJSON)),
    };
}

export function GetWebhookDeliverySummary200ResponseToJSON(json: any): GetWebhookDeliverySummary200Response {
    return GetWebhookDeliverySummary200ResponseToJSONTyped(json, false);
}

export function GetWebhookDeliverySummary200ResponseToJSONTyped(value?: GetWebhookDeliverySummary200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rangeDays': value['rangeDays'],
        'bucketCount': value['bucketCount'],
        'endpoints': ((value['endpoints'] as Array<any>).map(GetWebhookDeliverySummary200ResponseEndpointsInnerToJSON)),
    };
}

