/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Webhook } from './Webhook.js';
import {
    WebhookFromJSON,
    WebhookFromJSONTyped,
    WebhookToJSON,
    WebhookToJSONTyped,
} from './Webhook.js';

/**
 * 
 * @export
 * @interface GetWebhook200Response
 */
export interface GetWebhook200Response {
    /**
     * 
     */
    webhook: Webhook;
}

/**
 * Check if a given object implements the GetWebhook200Response interface.
 */
export function instanceOfGetWebhook200Response(value: object): value is GetWebhook200Response {
    if (!('webhook' in value) || value['webhook'] === undefined) return false;
    return true;
}

export function GetWebhook200ResponseFromJSON(json: any): GetWebhook200Response {
    return GetWebhook200ResponseFromJSONTyped(json, false);
}

export function GetWebhook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebhook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'webhook': WebhookFromJSON(json['webhook']),
    };
}

export function GetWebhook200ResponseToJSON(json: any): GetWebhook200Response {
    return GetWebhook200ResponseToJSONTyped(json, false);
}

export function GetWebhook200ResponseToJSONTyped(value?: GetWebhook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhook': WebhookToJSON(value['webhook']),
    };
}

