/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HideComment200ResponseHidden
 */
export interface HideComment200ResponseHidden {
    /**
     * 
     */
    postId: string;
    /**
     * 
     */
    destinationId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    commentId: string;
    /**
     * 
     */
    hidden: boolean;
}

/**
 * Check if a given object implements the HideComment200ResponseHidden interface.
 */
export function instanceOfHideComment200ResponseHidden(value: object): value is HideComment200ResponseHidden {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('commentId' in value) || value['commentId'] === undefined) return false;
    if (!('hidden' in value) || value['hidden'] === undefined) return false;
    return true;
}

export function HideComment200ResponseHiddenFromJSON(json: any): HideComment200ResponseHidden {
    return HideComment200ResponseHiddenFromJSONTyped(json, false);
}

export function HideComment200ResponseHiddenFromJSONTyped(json: any, ignoreDiscriminator: boolean): HideComment200ResponseHidden {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'destinationId': json['destinationId'],
        'platform': json['platform'],
        'commentId': json['commentId'],
        'hidden': json['hidden'],
    };
}

export function HideComment200ResponseHiddenToJSON(json: any): HideComment200ResponseHidden {
    return HideComment200ResponseHiddenToJSONTyped(json, false);
}

export function HideComment200ResponseHiddenToJSONTyped(value?: HideComment200ResponseHidden | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'destinationId': value['destinationId'],
        'platform': value['platform'],
        'commentId': value['commentId'],
        'hidden': value['hidden'],
    };
}

