/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { HideComment200ResponseHidden } from './HideComment200ResponseHidden.js';
import {
    HideComment200ResponseHiddenFromJSON,
    HideComment200ResponseHiddenFromJSONTyped,
    HideComment200ResponseHiddenToJSON,
    HideComment200ResponseHiddenToJSONTyped,
} from './HideComment200ResponseHidden.js';

/**
 * 
 * @export
 * @interface HideComment200Response
 */
export interface HideComment200Response {
    /**
     * 
     */
    hidden: HideComment200ResponseHidden;
}

/**
 * Check if a given object implements the HideComment200Response interface.
 */
export function instanceOfHideComment200Response(value: object): value is HideComment200Response {
    if (!('hidden' in value) || value['hidden'] === undefined) return false;
    return true;
}

export function HideComment200ResponseFromJSON(json: any): HideComment200Response {
    return HideComment200ResponseFromJSONTyped(json, false);
}

export function HideComment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HideComment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'hidden': HideComment200ResponseHiddenFromJSON(json['hidden']),
    };
}

export function HideComment200ResponseToJSON(json: any): HideComment200Response {
    return HideComment200ResponseToJSONTyped(json, false);
}

export function HideComment200ResponseToJSONTyped(value?: HideComment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hidden': HideComment200ResponseHiddenToJSON(value['hidden']),
    };
}

