/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface HideCommentRequest
 */
export interface HideCommentRequest {
    /**
     * Internal post id or platform-native post id. Native ids require accountId. Omit only when destinationId is passed on its own.
     */
    post?: string;
    /**
     * 
     */
    accountId?: string;
    /**
     * Globally unique destination id. Resolves on its own; post and accountId are optional alongside it.
     */
    destinationId?: string;
    /**
     * Platform-native comment id.
     */
    commentId: string;
    /**
     * 
     */
    hidden: boolean;
}

/**
 * Check if a given object implements the HideCommentRequest interface.
 */
export function instanceOfHideCommentRequest(value: object): value is HideCommentRequest {
    if (!('commentId' in value) || value['commentId'] === undefined) return false;
    if (!('hidden' in value) || value['hidden'] === undefined) return false;
    return true;
}

export function HideCommentRequestFromJSON(json: any): HideCommentRequest {
    return HideCommentRequestFromJSONTyped(json, false);
}

export function HideCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HideCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'post': json['post'] == null ? undefined : json['post'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'destinationId': json['destinationId'] == null ? undefined : json['destinationId'],
        'commentId': json['commentId'],
        'hidden': json['hidden'],
    };
}

export function HideCommentRequestToJSON(json: any): HideCommentRequest {
    return HideCommentRequestToJSONTyped(json, false);
}

export function HideCommentRequestToJSONTyped(value?: HideCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': value['post'],
        'accountId': value['accountId'],
        'destinationId': value['destinationId'],
        'commentId': value['commentId'],
        'hidden': value['hidden'],
    };
}

