/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListWebhookDeliveries200Response
 */
export interface ListWebhookDeliveries200Response {
    /**
     * 
     */
    deliveries: Array<any>;
}

/**
 * Check if a given object implements the ListWebhookDeliveries200Response interface.
 */
export function instanceOfListWebhookDeliveries200Response(value: object): value is ListWebhookDeliveries200Response {
    if (!('deliveries' in value) || value['deliveries'] === undefined) return false;
    return true;
}

export function ListWebhookDeliveries200ResponseFromJSON(json: any): ListWebhookDeliveries200Response {
    return ListWebhookDeliveries200ResponseFromJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookDeliveries200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'deliveries': json['deliveries'],
    };
}

export function ListWebhookDeliveries200ResponseToJSON(json: any): ListWebhookDeliveries200Response {
    return ListWebhookDeliveries200ResponseToJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseToJSONTyped(value?: ListWebhookDeliveries200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deliveries': value['deliveries'],
    };
}

