/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListPosts200ResponseFacetsStatusInner } from './ListPosts200ResponseFacetsStatusInner.js';
import {
    ListPosts200ResponseFacetsStatusInnerFromJSON,
    ListPosts200ResponseFacetsStatusInnerFromJSONTyped,
    ListPosts200ResponseFacetsStatusInnerToJSON,
    ListPosts200ResponseFacetsStatusInnerToJSONTyped,
} from './ListPosts200ResponseFacetsStatusInner.js';

/**
 * 
 * @export
 * @interface ListWebhookDeliveries200ResponseFacets
 */
export interface ListWebhookDeliveries200ResponseFacets {
    /**
     * 
     */
    status: Array<ListPosts200ResponseFacetsStatusInner>;
}

/**
 * Check if a given object implements the ListWebhookDeliveries200ResponseFacets interface.
 */
export function instanceOfListWebhookDeliveries200ResponseFacets(value: object): value is ListWebhookDeliveries200ResponseFacets {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ListWebhookDeliveries200ResponseFacetsFromJSON(json: any): ListWebhookDeliveries200ResponseFacets {
    return ListWebhookDeliveries200ResponseFacetsFromJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseFacetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookDeliveries200ResponseFacets {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ((json['status'] as Array<any>).map(ListPosts200ResponseFacetsStatusInnerFromJSON)),
    };
}

export function ListWebhookDeliveries200ResponseFacetsToJSON(json: any): ListWebhookDeliveries200ResponseFacets {
    return ListWebhookDeliveries200ResponseFacetsToJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseFacetsToJSONTyped(value?: ListWebhookDeliveries200ResponseFacets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ((value['status'] as Array<any>).map(ListPosts200ResponseFacetsStatusInnerToJSON)),
    };
}

