/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListWebhookDeliveries200ResponseFacetsStatusInner
 */
export interface ListWebhookDeliveries200ResponseFacetsStatusInner {
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    count: number;
}

/**
 * Check if a given object implements the ListWebhookDeliveries200ResponseFacetsStatusInner interface.
 */
export function instanceOfListWebhookDeliveries200ResponseFacetsStatusInner(value: object): value is ListWebhookDeliveries200ResponseFacetsStatusInner {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ListWebhookDeliveries200ResponseFacetsStatusInnerFromJSON(json: any): ListWebhookDeliveries200ResponseFacetsStatusInner {
    return ListWebhookDeliveries200ResponseFacetsStatusInnerFromJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseFacetsStatusInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookDeliveries200ResponseFacetsStatusInner {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'count': json['count'],
    };
}

export function ListWebhookDeliveries200ResponseFacetsStatusInnerToJSON(json: any): ListWebhookDeliveries200ResponseFacetsStatusInner {
    return ListWebhookDeliveries200ResponseFacetsStatusInnerToJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseFacetsStatusInnerToJSONTyped(value?: ListWebhookDeliveries200ResponseFacetsStatusInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'count': value['count'],
    };
}

