/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListPosts200ResponseFacetsStatusInner
 */
export interface ListPosts200ResponseFacetsStatusInner {
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    count: number;
}

/**
 * Check if a given object implements the ListPosts200ResponseFacetsStatusInner interface.
 */
export function instanceOfListPosts200ResponseFacetsStatusInner(value: object): value is ListPosts200ResponseFacetsStatusInner {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ListPosts200ResponseFacetsStatusInnerFromJSON(json: any): ListPosts200ResponseFacetsStatusInner {
    return ListPosts200ResponseFacetsStatusInnerFromJSONTyped(json, false);
}

export function ListPosts200ResponseFacetsStatusInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPosts200ResponseFacetsStatusInner {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'count': json['count'],
    };
}

export function ListPosts200ResponseFacetsStatusInnerToJSON(json: any): ListPosts200ResponseFacetsStatusInner {
    return ListPosts200ResponseFacetsStatusInnerToJSONTyped(json, false);
}

export function ListPosts200ResponseFacetsStatusInnerToJSONTyped(value?: ListPosts200ResponseFacetsStatusInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'count': value['count'],
    };
}

