/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { ListPinterestBoards200ResponseBoardsInner } from './ListPinterestBoards200ResponseBoardsInner.js';
import {
    ListPinterestBoards200ResponseBoardsInnerFromJSON,
    ListPinterestBoards200ResponseBoardsInnerFromJSONTyped,
    ListPinterestBoards200ResponseBoardsInnerToJSON,
    ListPinterestBoards200ResponseBoardsInnerToJSONTyped,
} from './ListPinterestBoards200ResponseBoardsInner.js';

/**
 * 
 * @export
 * @interface ListPinterestBoards200Response
 */
export interface ListPinterestBoards200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: ListPinterestBoards200ResponsePlatformEnum;
    /**
     * 
     */
    boards: Array<ListPinterestBoards200ResponseBoardsInner>;
    /**
     * 
     */
    defaultBoardId: string | null;
    /**
     * 
     */
    sandbox: boolean;
    /**
     * 
     */
    fetchedAt: Date;
}


/**
 * @export
 */
export const ListPinterestBoards200ResponsePlatformEnum = {
    Pinterest: 'pinterest',
} as const;
export type ListPinterestBoards200ResponsePlatformEnum = typeof ListPinterestBoards200ResponsePlatformEnum[keyof typeof ListPinterestBoards200ResponsePlatformEnum];


/**
 * Check if a given object implements the ListPinterestBoards200Response interface.
 */
export function instanceOfListPinterestBoards200Response(value: object): value is ListPinterestBoards200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (value['platform'] !== 'pinterest') return false;
    
    if (!('boards' in value) || value['boards'] === undefined) return false;
    if (!('defaultBoardId' in value) || value['defaultBoardId'] === undefined) return false;
    if (!('sandbox' in value) || value['sandbox'] === undefined) return false;
    if (!('fetchedAt' in value) || value['fetchedAt'] === undefined) return false;
    return true;
}

export function ListPinterestBoards200ResponseFromJSON(json: any): ListPinterestBoards200Response {
    return ListPinterestBoards200ResponseFromJSONTyped(json, false);
}

export function ListPinterestBoards200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPinterestBoards200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'platform': json['platform'],
        'boards': ((json['boards'] as Array<any>).map(ListPinterestBoards200ResponseBoardsInnerFromJSON)),
        'defaultBoardId': json['defaultBoardId'],
        'sandbox': json['sandbox'],
        'fetchedAt': (json['fetchedAt'] == null ? json['fetchedAt'] : parseDateTime(json['fetchedAt'])),
    };
}

export function ListPinterestBoards200ResponseToJSON(json: any): ListPinterestBoards200Response {
    return ListPinterestBoards200ResponseToJSONTyped(json, false);
}

export function ListPinterestBoards200ResponseToJSONTyped(value?: ListPinterestBoards200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'platform': value['platform'],
        'boards': ((value['boards'] as Array<any>).map(ListPinterestBoards200ResponseBoardsInnerToJSON)),
        'defaultBoardId': value['defaultBoardId'],
        'sandbox': value['sandbox'],
        'fetchedAt': value['fetchedAt'] == null ? value['fetchedAt'] : serializeDateTime(value['fetchedAt']),
    };
}

