/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListAutomations200ResponseRulesInner
 */
export interface ListAutomations200ResponseRulesInner {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    kind: ListAutomations200ResponseRulesInnerKindEnum;
    /**
     * Case-insensitive substring triggers. Empty means every comment or message matches.
     */
    keywords: Array<string>;
    /**
     * Skip the rule when the comment or message contains any of these.
     */
    excludeKeywords: Array<string>;
    /**
     * 
     */
    dmMessage: string;
    /**
     * 
     */
    enabled: boolean;
    /**
     * 
     */
    accountId: string;
}


/**
 * @export
 */
export const ListAutomations200ResponseRulesInnerKindEnum = {
    CommentToDm: 'comment_to_dm',
    StoryReply: 'story_reply',
    WelcomeDm: 'welcome_dm',
} as const;
export type ListAutomations200ResponseRulesInnerKindEnum = typeof ListAutomations200ResponseRulesInnerKindEnum[keyof typeof ListAutomations200ResponseRulesInnerKindEnum];


/**
 * Check if a given object implements the ListAutomations200ResponseRulesInner interface.
 */
export function instanceOfListAutomations200ResponseRulesInner(value: object): value is ListAutomations200ResponseRulesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    if (!('excludeKeywords' in value) || value['excludeKeywords'] === undefined) return false;
    if (!('dmMessage' in value) || value['dmMessage'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    return true;
}

export function ListAutomations200ResponseRulesInnerFromJSON(json: any): ListAutomations200ResponseRulesInner {
    return ListAutomations200ResponseRulesInnerFromJSONTyped(json, false);
}

export function ListAutomations200ResponseRulesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAutomations200ResponseRulesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'kind': json['kind'],
        'keywords': json['keywords'],
        'excludeKeywords': json['excludeKeywords'],
        'dmMessage': json['dmMessage'],
        'enabled': json['enabled'],
        'accountId': json['accountId'],
    };
}

export function ListAutomations200ResponseRulesInnerToJSON(json: any): ListAutomations200ResponseRulesInner {
    return ListAutomations200ResponseRulesInnerToJSONTyped(json, false);
}

export function ListAutomations200ResponseRulesInnerToJSONTyped(value?: ListAutomations200ResponseRulesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'kind': value['kind'],
        'keywords': value['keywords'],
        'excludeKeywords': value['excludeKeywords'],
        'dmMessage': value['dmMessage'],
        'enabled': value['enabled'],
        'accountId': value['accountId'],
    };
}

