/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListInboxMessages200ResponseMessagesInner } from './ListInboxMessages200ResponseMessagesInner.js';
import {
    ListInboxMessages200ResponseMessagesInnerFromJSON,
    ListInboxMessages200ResponseMessagesInnerFromJSONTyped,
    ListInboxMessages200ResponseMessagesInnerToJSON,
    ListInboxMessages200ResponseMessagesInnerToJSONTyped,
} from './ListInboxMessages200ResponseMessagesInner.js';

/**
 * 
 * @export
 * @interface ListInboxMessages200Response
 */
export interface ListInboxMessages200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    convoId: string;
    /**
     * 
     */
    messages: Array<ListInboxMessages200ResponseMessagesInner>;
    /**
     * 
     */
    cursor: string | null;
}

/**
 * Check if a given object implements the ListInboxMessages200Response interface.
 */
export function instanceOfListInboxMessages200Response(value: object): value is ListInboxMessages200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('convoId' in value) || value['convoId'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    if (!('cursor' in value) || value['cursor'] === undefined) return false;
    return true;
}

export function ListInboxMessages200ResponseFromJSON(json: any): ListInboxMessages200Response {
    return ListInboxMessages200ResponseFromJSONTyped(json, false);
}

export function ListInboxMessages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInboxMessages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'convoId': json['convoId'],
        'messages': ((json['messages'] as Array<any>).map(ListInboxMessages200ResponseMessagesInnerFromJSON)),
        'cursor': json['cursor'],
    };
}

export function ListInboxMessages200ResponseToJSON(json: any): ListInboxMessages200Response {
    return ListInboxMessages200ResponseToJSONTyped(json, false);
}

export function ListInboxMessages200ResponseToJSONTyped(value?: ListInboxMessages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'convoId': value['convoId'],
        'messages': ((value['messages'] as Array<any>).map(ListInboxMessages200ResponseMessagesInnerToJSON)),
        'cursor': value['cursor'],
    };
}

