/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Actor } from './Actor.js';
import {
    ActorFromJSON,
    ActorFromJSONTyped,
    ActorToJSON,
    ActorToJSONTyped,
} from './Actor.js';

/**
 * 
 * @export
 * @interface ListRetweeters200ResponseRetweetsSubjectsInner
 */
export interface ListRetweeters200ResponseRetweetsSubjectsInner {
    /**
     * 
     */
    scope: ListRetweeters200ResponseRetweetsSubjectsInnerScopeEnum;
    /**
     * 
     */
    subjectId: string;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    actors?: Array<Actor>;
    /**
     * 
     */
    nextCursor?: string | null;
}


/**
 * @export
 */
export const ListRetweeters200ResponseRetweetsSubjectsInnerScopeEnum = {
    Destination: 'destination',
    External: 'external',
} as const;
export type ListRetweeters200ResponseRetweetsSubjectsInnerScopeEnum = typeof ListRetweeters200ResponseRetweetsSubjectsInnerScopeEnum[keyof typeof ListRetweeters200ResponseRetweetsSubjectsInnerScopeEnum];


/**
 * Check if a given object implements the ListRetweeters200ResponseRetweetsSubjectsInner interface.
 */
export function instanceOfListRetweeters200ResponseRetweetsSubjectsInner(value: object): value is ListRetweeters200ResponseRetweetsSubjectsInner {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    return true;
}

export function ListRetweeters200ResponseRetweetsSubjectsInnerFromJSON(json: any): ListRetweeters200ResponseRetweetsSubjectsInner {
    return ListRetweeters200ResponseRetweetsSubjectsInnerFromJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsSubjectsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRetweeters200ResponseRetweetsSubjectsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
        'subjectId': json['subjectId'],
        'status': json['status'] == null ? undefined : json['status'],
        'actors': json['actors'] == null ? undefined : ((json['actors'] as Array<any>).map(ActorFromJSON)),
        'nextCursor': json['nextCursor'] === undefined ? undefined : json['nextCursor'] === null ? null : json['nextCursor'],
    };
}

export function ListRetweeters200ResponseRetweetsSubjectsInnerToJSON(json: any): ListRetweeters200ResponseRetweetsSubjectsInner {
    return ListRetweeters200ResponseRetweetsSubjectsInnerToJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsSubjectsInnerToJSONTyped(value?: ListRetweeters200ResponseRetweetsSubjectsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'subjectId': value['subjectId'],
        'status': value['status'],
        'actors': value['actors'] == null ? undefined : ((value['actors'] as Array<any>).map(ActorToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

