/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListComments200Response
 */
export interface ListComments200Response {
    /**
     * 
     */
    comments?: any | null;
}

/**
 * Check if a given object implements the ListComments200Response interface.
 */
export function instanceOfListComments200Response(value: object): value is ListComments200Response {
    return true;
}

export function ListComments200ResponseFromJSON(json: any): ListComments200Response {
    return ListComments200ResponseFromJSONTyped(json, false);
}

export function ListComments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListComments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'] === undefined ? undefined : json['comments'] === null ? null : json['comments'],
    };
}

export function ListComments200ResponseToJSON(json: any): ListComments200Response {
    return ListComments200ResponseToJSONTyped(json, false);
}

export function ListComments200ResponseToJSONTyped(value?: ListComments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': value['comments'],
    };
}

