/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListWebhookDeliveries200ResponseHistogramInner
 */
export interface ListWebhookDeliveries200ResponseHistogramInner {
    /**
     * 
     */
    bucket: string;
    /**
     * 
     */
    success: number;
    /**
     * 
     */
    failed: number;
}

/**
 * Check if a given object implements the ListWebhookDeliveries200ResponseHistogramInner interface.
 */
export function instanceOfListWebhookDeliveries200ResponseHistogramInner(value: object): value is ListWebhookDeliveries200ResponseHistogramInner {
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    return true;
}

export function ListWebhookDeliveries200ResponseHistogramInnerFromJSON(json: any): ListWebhookDeliveries200ResponseHistogramInner {
    return ListWebhookDeliveries200ResponseHistogramInnerFromJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseHistogramInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookDeliveries200ResponseHistogramInner {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket': json['bucket'],
        'success': json['success'],
        'failed': json['failed'],
    };
}

export function ListWebhookDeliveries200ResponseHistogramInnerToJSON(json: any): ListWebhookDeliveries200ResponseHistogramInner {
    return ListWebhookDeliveries200ResponseHistogramInnerToJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseHistogramInnerToJSONTyped(value?: ListWebhookDeliveries200ResponseHistogramInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket': value['bucket'],
        'success': value['success'],
        'failed': value['failed'],
    };
}

