/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListConnectionMedia200Response
 */
export interface ListConnectionMedia200Response {
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    items: Array<{ [key: string]: any | null; }>;
    /**
     * 
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the ListConnectionMedia200Response interface.
 */
export function instanceOfListConnectionMedia200Response(value: object): value is ListConnectionMedia200Response {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function ListConnectionMedia200ResponseFromJSON(json: any): ListConnectionMedia200Response {
    return ListConnectionMedia200ResponseFromJSONTyped(json, false);
}

export function ListConnectionMedia200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectionMedia200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
        'platform': json['platform'],
        'items': json['items'],
        'nextCursor': json['nextCursor'],
    };
}

export function ListConnectionMedia200ResponseToJSON(json: any): ListConnectionMedia200Response {
    return ListConnectionMedia200ResponseToJSONTyped(json, false);
}

export function ListConnectionMedia200ResponseToJSONTyped(value?: ListConnectionMedia200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectionId': value['connectionId'],
        'platform': value['platform'],
        'items': value['items'],
        'nextCursor': value['nextCursor'],
    };
}

