/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListProfiles403ResponseError } from './ListProfiles403ResponseError.js';
import {
    ListProfiles403ResponseErrorFromJSON,
    ListProfiles403ResponseErrorFromJSONTyped,
    ListProfiles403ResponseErrorToJSON,
    ListProfiles403ResponseErrorToJSONTyped,
} from './ListProfiles403ResponseError.js';

/**
 * 
 * @export
 * @interface ListProfiles403Response
 */
export interface ListProfiles403Response {
    /**
     * 
     */
    error: ListProfiles403ResponseError;
}

/**
 * Check if a given object implements the ListProfiles403Response interface.
 */
export function instanceOfListProfiles403Response(value: object): value is ListProfiles403Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ListProfiles403ResponseFromJSON(json: any): ListProfiles403Response {
    return ListProfiles403ResponseFromJSONTyped(json, false);
}

export function ListProfiles403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProfiles403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': ListProfiles403ResponseErrorFromJSON(json['error']),
    };
}

export function ListProfiles403ResponseToJSON(json: any): ListProfiles403Response {
    return ListProfiles403ResponseToJSONTyped(json, false);
}

export function ListProfiles403ResponseToJSONTyped(value?: ListProfiles403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': ListProfiles403ResponseErrorToJSON(value['error']),
    };
}

