/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListRetweeters200ResponseRetweetsDestinationsInner } from './ListRetweeters200ResponseRetweetsDestinationsInner.js';
import {
    ListRetweeters200ResponseRetweetsDestinationsInnerFromJSON,
    ListRetweeters200ResponseRetweetsDestinationsInnerFromJSONTyped,
    ListRetweeters200ResponseRetweetsDestinationsInnerToJSON,
    ListRetweeters200ResponseRetweetsDestinationsInnerToJSONTyped,
} from './ListRetweeters200ResponseRetweetsDestinationsInner.js';

/**
 * 
 * @export
 * @interface ListRetweeters200ResponseRetweets
 */
export interface ListRetweeters200ResponseRetweets {
    /**
     * 
     */
    postId?: string;
    /**
     * 
     */
    destinations?: Array<ListRetweeters200ResponseRetweetsDestinationsInner>;
}

/**
 * Check if a given object implements the ListRetweeters200ResponseRetweets interface.
 */
export function instanceOfListRetweeters200ResponseRetweets(value: object): value is ListRetweeters200ResponseRetweets {
    return true;
}

export function ListRetweeters200ResponseRetweetsFromJSON(json: any): ListRetweeters200ResponseRetweets {
    return ListRetweeters200ResponseRetweetsFromJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRetweeters200ResponseRetweets {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'] == null ? undefined : json['postId'],
        'destinations': json['destinations'] == null ? undefined : ((json['destinations'] as Array<any>).map(ListRetweeters200ResponseRetweetsDestinationsInnerFromJSON)),
    };
}

export function ListRetweeters200ResponseRetweetsToJSON(json: any): ListRetweeters200ResponseRetweets {
    return ListRetweeters200ResponseRetweetsToJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsToJSONTyped(value?: ListRetweeters200ResponseRetweets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'destinations': value['destinations'] == null ? undefined : ((value['destinations'] as Array<any>).map(ListRetweeters200ResponseRetweetsDestinationsInnerToJSON)),
    };
}

