/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListInstagramAccounts200ResponseAccountsInner } from './ListInstagramAccounts200ResponseAccountsInner.js';
import {
    ListInstagramAccounts200ResponseAccountsInnerFromJSON,
    ListInstagramAccounts200ResponseAccountsInnerFromJSONTyped,
    ListInstagramAccounts200ResponseAccountsInnerToJSON,
    ListInstagramAccounts200ResponseAccountsInnerToJSONTyped,
} from './ListInstagramAccounts200ResponseAccountsInner.js';

/**
 * 
 * @export
 * @interface ListInstagramAccounts200Response
 */
export interface ListInstagramAccounts200Response {
    /**
     * 
     */
    accounts: Array<ListInstagramAccounts200ResponseAccountsInner>;
}

/**
 * Check if a given object implements the ListInstagramAccounts200Response interface.
 */
export function instanceOfListInstagramAccounts200Response(value: object): value is ListInstagramAccounts200Response {
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function ListInstagramAccounts200ResponseFromJSON(json: any): ListInstagramAccounts200Response {
    return ListInstagramAccounts200ResponseFromJSONTyped(json, false);
}

export function ListInstagramAccounts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInstagramAccounts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accounts': ((json['accounts'] as Array<any>).map(ListInstagramAccounts200ResponseAccountsInnerFromJSON)),
    };
}

export function ListInstagramAccounts200ResponseToJSON(json: any): ListInstagramAccounts200Response {
    return ListInstagramAccounts200ResponseToJSONTyped(json, false);
}

export function ListInstagramAccounts200ResponseToJSONTyped(value?: ListInstagramAccounts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accounts': ((value['accounts'] as Array<any>).map(ListInstagramAccounts200ResponseAccountsInnerToJSON)),
    };
}

