/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListWebhookEventTypes200Response
 */
export interface ListWebhookEventTypes200Response {
    /**
     * 
     */
    events: Array<string>;
    /**
     * 
     */
    groups: Array<any>;
}

/**
 * Check if a given object implements the ListWebhookEventTypes200Response interface.
 */
export function instanceOfListWebhookEventTypes200Response(value: object): value is ListWebhookEventTypes200Response {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('groups' in value) || value['groups'] === undefined) return false;
    return true;
}

export function ListWebhookEventTypes200ResponseFromJSON(json: any): ListWebhookEventTypes200Response {
    return ListWebhookEventTypes200ResponseFromJSONTyped(json, false);
}

export function ListWebhookEventTypes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookEventTypes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'events': json['events'],
        'groups': json['groups'],
    };
}

export function ListWebhookEventTypes200ResponseToJSON(json: any): ListWebhookEventTypes200Response {
    return ListWebhookEventTypes200ResponseToJSONTyped(json, false);
}

export function ListWebhookEventTypes200ResponseToJSONTyped(value?: ListWebhookEventTypes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'],
        'groups': value['groups'],
    };
}

