/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListConnectionMedia200ResponseItemsInnerMetrics } from './ListConnectionMedia200ResponseItemsInnerMetrics.js';
import {
    ListConnectionMedia200ResponseItemsInnerMetricsFromJSON,
    ListConnectionMedia200ResponseItemsInnerMetricsFromJSONTyped,
    ListConnectionMedia200ResponseItemsInnerMetricsToJSON,
    ListConnectionMedia200ResponseItemsInnerMetricsToJSONTyped,
} from './ListConnectionMedia200ResponseItemsInnerMetrics.js';

/**
 * 
 * @export
 * @interface ListConnectionMedia200ResponseItemsInner
 */
export interface ListConnectionMedia200ResponseItemsInner {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    title: string | null;
    /**
     * 
     */
    description: string | null;
    /**
     * 
     */
    coverUrl: string | null;
    /**
     * 
     */
    shareUrl: string | null;
    /**
     * 
     */
    createdAt: string | null;
    /**
     * 
     */
    durationSec: number | null;
    /**
     * 
     */
    metrics: ListConnectionMedia200ResponseItemsInnerMetrics;
}

/**
 * Check if a given object implements the ListConnectionMedia200ResponseItemsInner interface.
 */
export function instanceOfListConnectionMedia200ResponseItemsInner(value: object): value is ListConnectionMedia200ResponseItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('coverUrl' in value) || value['coverUrl'] === undefined) return false;
    if (!('shareUrl' in value) || value['shareUrl'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('durationSec' in value) || value['durationSec'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    return true;
}

export function ListConnectionMedia200ResponseItemsInnerFromJSON(json: any): ListConnectionMedia200ResponseItemsInner {
    return ListConnectionMedia200ResponseItemsInnerFromJSONTyped(json, false);
}

export function ListConnectionMedia200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectionMedia200ResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'coverUrl': json['coverUrl'],
        'shareUrl': json['shareUrl'],
        'createdAt': json['createdAt'],
        'durationSec': json['durationSec'],
        'metrics': ListConnectionMedia200ResponseItemsInnerMetricsFromJSON(json['metrics']),
    };
}

export function ListConnectionMedia200ResponseItemsInnerToJSON(json: any): ListConnectionMedia200ResponseItemsInner {
    return ListConnectionMedia200ResponseItemsInnerToJSONTyped(json, false);
}

export function ListConnectionMedia200ResponseItemsInnerToJSONTyped(value?: ListConnectionMedia200ResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'coverUrl': value['coverUrl'],
        'shareUrl': value['shareUrl'],
        'createdAt': value['createdAt'],
        'durationSec': value['durationSec'],
        'metrics': ListConnectionMedia200ResponseItemsInnerMetricsToJSON(value['metrics']),
    };
}

