/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Actor } from './Actor.js';
import {
    ActorFromJSON,
    ActorFromJSONTyped,
    ActorToJSON,
    ActorToJSONTyped,
} from './Actor.js';

/**
 * 
 * @export
 * @interface ListRetweeters200ResponseRetweetsDestinationsInner
 */
export interface ListRetweeters200ResponseRetweetsDestinationsInner {
    /**
     * 
     */
    destinationId: string;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    actors?: Array<Actor>;
    /**
     * 
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the ListRetweeters200ResponseRetweetsDestinationsInner interface.
 */
export function instanceOfListRetweeters200ResponseRetweetsDestinationsInner(value: object): value is ListRetweeters200ResponseRetweetsDestinationsInner {
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    return true;
}

export function ListRetweeters200ResponseRetweetsDestinationsInnerFromJSON(json: any): ListRetweeters200ResponseRetweetsDestinationsInner {
    return ListRetweeters200ResponseRetweetsDestinationsInnerFromJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsDestinationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRetweeters200ResponseRetweetsDestinationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationId': json['destinationId'],
        'status': json['status'] == null ? undefined : json['status'],
        'actors': json['actors'] == null ? undefined : ((json['actors'] as Array<any>).map(ActorFromJSON)),
        'nextCursor': json['nextCursor'] === undefined ? undefined : json['nextCursor'] === null ? null : json['nextCursor'],
    };
}

export function ListRetweeters200ResponseRetweetsDestinationsInnerToJSON(json: any): ListRetweeters200ResponseRetweetsDestinationsInner {
    return ListRetweeters200ResponseRetweetsDestinationsInnerToJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsDestinationsInnerToJSONTyped(value?: ListRetweeters200ResponseRetweetsDestinationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationId': value['destinationId'],
        'status': value['status'],
        'actors': value['actors'] == null ? undefined : ((value['actors'] as Array<any>).map(ActorToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

