/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListFacebookPages200ResponsePagesInner } from './ListFacebookPages200ResponsePagesInner.js';
import {
    ListFacebookPages200ResponsePagesInnerFromJSON,
    ListFacebookPages200ResponsePagesInnerFromJSONTyped,
    ListFacebookPages200ResponsePagesInnerToJSON,
    ListFacebookPages200ResponsePagesInnerToJSONTyped,
} from './ListFacebookPages200ResponsePagesInner.js';

/**
 * 
 * @export
 * @interface ListFacebookPages200Response
 */
export interface ListFacebookPages200Response {
    /**
     * 
     */
    pages: Array<ListFacebookPages200ResponsePagesInner>;
}

/**
 * Check if a given object implements the ListFacebookPages200Response interface.
 */
export function instanceOfListFacebookPages200Response(value: object): value is ListFacebookPages200Response {
    if (!('pages' in value) || value['pages'] === undefined) return false;
    return true;
}

export function ListFacebookPages200ResponseFromJSON(json: any): ListFacebookPages200Response {
    return ListFacebookPages200ResponseFromJSONTyped(json, false);
}

export function ListFacebookPages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFacebookPages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pages': ((json['pages'] as Array<any>).map(ListFacebookPages200ResponsePagesInnerFromJSON)),
    };
}

export function ListFacebookPages200ResponseToJSON(json: any): ListFacebookPages200Response {
    return ListFacebookPages200ResponseToJSONTyped(json, false);
}

export function ListFacebookPages200ResponseToJSONTyped(value?: ListFacebookPages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pages': ((value['pages'] as Array<any>).map(ListFacebookPages200ResponsePagesInnerToJSON)),
    };
}

