/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListInboxConversations200ResponseConvosInner } from './ListInboxConversations200ResponseConvosInner.js';
import {
    ListInboxConversations200ResponseConvosInnerFromJSON,
    ListInboxConversations200ResponseConvosInnerFromJSONTyped,
    ListInboxConversations200ResponseConvosInnerToJSON,
    ListInboxConversations200ResponseConvosInnerToJSONTyped,
} from './ListInboxConversations200ResponseConvosInner.js';

/**
 * 
 * @export
 * @interface ListInboxConversations200Response
 */
export interface ListInboxConversations200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    convos: Array<ListInboxConversations200ResponseConvosInner>;
    /**
     * 
     */
    cursor: string | null;
}

/**
 * Check if a given object implements the ListInboxConversations200Response interface.
 */
export function instanceOfListInboxConversations200Response(value: object): value is ListInboxConversations200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('convos' in value) || value['convos'] === undefined) return false;
    if (!('cursor' in value) || value['cursor'] === undefined) return false;
    return true;
}

export function ListInboxConversations200ResponseFromJSON(json: any): ListInboxConversations200Response {
    return ListInboxConversations200ResponseFromJSONTyped(json, false);
}

export function ListInboxConversations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInboxConversations200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'convos': ((json['convos'] as Array<any>).map(ListInboxConversations200ResponseConvosInnerFromJSON)),
        'cursor': json['cursor'],
    };
}

export function ListInboxConversations200ResponseToJSON(json: any): ListInboxConversations200Response {
    return ListInboxConversations200ResponseToJSONTyped(json, false);
}

export function ListInboxConversations200ResponseToJSONTyped(value?: ListInboxConversations200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'convos': ((value['convos'] as Array<any>).map(ListInboxConversations200ResponseConvosInnerToJSON)),
        'cursor': value['cursor'],
    };
}

