/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListPosts200ResponseFacetsPlatformInner
 */
export interface ListPosts200ResponseFacetsPlatformInner {
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    count: number;
}

/**
 * Check if a given object implements the ListPosts200ResponseFacetsPlatformInner interface.
 */
export function instanceOfListPosts200ResponseFacetsPlatformInner(value: object): value is ListPosts200ResponseFacetsPlatformInner {
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ListPosts200ResponseFacetsPlatformInnerFromJSON(json: any): ListPosts200ResponseFacetsPlatformInner {
    return ListPosts200ResponseFacetsPlatformInnerFromJSONTyped(json, false);
}

export function ListPosts200ResponseFacetsPlatformInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPosts200ResponseFacetsPlatformInner {
    if (json == null) {
        return json;
    }
    return {
        
        'platform': json['platform'],
        'count': json['count'],
    };
}

export function ListPosts200ResponseFacetsPlatformInnerToJSON(json: any): ListPosts200ResponseFacetsPlatformInner {
    return ListPosts200ResponseFacetsPlatformInnerToJSONTyped(json, false);
}

export function ListPosts200ResponseFacetsPlatformInnerToJSONTyped(value?: ListPosts200ResponseFacetsPlatformInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform': value['platform'],
        'count': value['count'],
    };
}

