/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListRetweeters200ResponseRetweetsSubjectsInner } from './ListRetweeters200ResponseRetweetsSubjectsInner.js';
import {
    ListRetweeters200ResponseRetweetsSubjectsInnerFromJSON,
    ListRetweeters200ResponseRetweetsSubjectsInnerFromJSONTyped,
    ListRetweeters200ResponseRetweetsSubjectsInnerToJSON,
    ListRetweeters200ResponseRetweetsSubjectsInnerToJSONTyped,
} from './ListRetweeters200ResponseRetweetsSubjectsInner.js';

/**
 * 
 * @export
 * @interface ListRetweeters200ResponseRetweets
 */
export interface ListRetweeters200ResponseRetweets {
    /**
     * 
     */
    post: string;
    /**
     * 
     */
    subjects?: Array<ListRetweeters200ResponseRetweetsSubjectsInner>;
}

/**
 * Check if a given object implements the ListRetweeters200ResponseRetweets interface.
 */
export function instanceOfListRetweeters200ResponseRetweets(value: object): value is ListRetweeters200ResponseRetweets {
    if (!('post' in value) || value['post'] === undefined) return false;
    return true;
}

export function ListRetweeters200ResponseRetweetsFromJSON(json: any): ListRetweeters200ResponseRetweets {
    return ListRetweeters200ResponseRetweetsFromJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRetweeters200ResponseRetweets {
    if (json == null) {
        return json;
    }
    return {
        
        'post': json['post'],
        'subjects': json['subjects'] == null ? undefined : ((json['subjects'] as Array<any>).map(ListRetweeters200ResponseRetweetsSubjectsInnerFromJSON)),
    };
}

export function ListRetweeters200ResponseRetweetsToJSON(json: any): ListRetweeters200ResponseRetweets {
    return ListRetweeters200ResponseRetweetsToJSONTyped(json, false);
}

export function ListRetweeters200ResponseRetweetsToJSONTyped(value?: ListRetweeters200ResponseRetweets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': value['post'],
        'subjects': value['subjects'] == null ? undefined : ((value['subjects'] as Array<any>).map(ListRetweeters200ResponseRetweetsSubjectsInnerToJSON)),
    };
}

