/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListFacebookPages200ResponsePagesInner
 */
export interface ListFacebookPages200ResponsePagesInner {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    username: string | null;
    /**
     * 
     */
    category: string | null;
    /**
     * 
     */
    pictureUrl: string | null;
}

/**
 * Check if a given object implements the ListFacebookPages200ResponsePagesInner interface.
 */
export function instanceOfListFacebookPages200ResponsePagesInner(value: object): value is ListFacebookPages200ResponsePagesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('pictureUrl' in value) || value['pictureUrl'] === undefined) return false;
    return true;
}

export function ListFacebookPages200ResponsePagesInnerFromJSON(json: any): ListFacebookPages200ResponsePagesInner {
    return ListFacebookPages200ResponsePagesInnerFromJSONTyped(json, false);
}

export function ListFacebookPages200ResponsePagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFacebookPages200ResponsePagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'username': json['username'],
        'category': json['category'],
        'pictureUrl': json['pictureUrl'],
    };
}

export function ListFacebookPages200ResponsePagesInnerToJSON(json: any): ListFacebookPages200ResponsePagesInner {
    return ListFacebookPages200ResponsePagesInnerToJSONTyped(json, false);
}

export function ListFacebookPages200ResponsePagesInnerToJSONTyped(value?: ListFacebookPages200ResponsePagesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'username': value['username'],
        'category': value['category'],
        'pictureUrl': value['pictureUrl'],
    };
}

