/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListInboxMessages200ResponseMessagesInnerAttachmentsInner
 */
export interface ListInboxMessages200ResponseMessagesInnerAttachmentsInner {
    /**
     * 
     */
    type: ListInboxMessages200ResponseMessagesInnerAttachmentsInnerTypeEnum;
    /**
     * 
     */
    url: string | null;
}


/**
 * @export
 */
export const ListInboxMessages200ResponseMessagesInnerAttachmentsInnerTypeEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    File: 'file',
    Other: 'other',
} as const;
export type ListInboxMessages200ResponseMessagesInnerAttachmentsInnerTypeEnum = typeof ListInboxMessages200ResponseMessagesInnerAttachmentsInnerTypeEnum[keyof typeof ListInboxMessages200ResponseMessagesInnerAttachmentsInnerTypeEnum];


/**
 * Check if a given object implements the ListInboxMessages200ResponseMessagesInnerAttachmentsInner interface.
 */
export function instanceOfListInboxMessages200ResponseMessagesInnerAttachmentsInner(value: object): value is ListInboxMessages200ResponseMessagesInnerAttachmentsInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ListInboxMessages200ResponseMessagesInnerAttachmentsInnerFromJSON(json: any): ListInboxMessages200ResponseMessagesInnerAttachmentsInner {
    return ListInboxMessages200ResponseMessagesInnerAttachmentsInnerFromJSONTyped(json, false);
}

export function ListInboxMessages200ResponseMessagesInnerAttachmentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInboxMessages200ResponseMessagesInnerAttachmentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'url': json['url'],
    };
}

export function ListInboxMessages200ResponseMessagesInnerAttachmentsInnerToJSON(json: any): ListInboxMessages200ResponseMessagesInnerAttachmentsInner {
    return ListInboxMessages200ResponseMessagesInnerAttachmentsInnerToJSONTyped(json, false);
}

export function ListInboxMessages200ResponseMessagesInnerAttachmentsInnerToJSONTyped(value?: ListInboxMessages200ResponseMessagesInnerAttachmentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'url': value['url'],
    };
}

