/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Comment } from './Comment.js';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
    CommentToJSONTyped,
} from './Comment.js';
import type { GetAnalytics200ResponseAnalyticsSubjectsInnerError } from './GetAnalytics200ResponseAnalyticsSubjectsInnerError.js';
import {
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorFromJSON,
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorFromJSONTyped,
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorToJSON,
    GetAnalytics200ResponseAnalyticsSubjectsInnerErrorToJSONTyped,
} from './GetAnalytics200ResponseAnalyticsSubjectsInnerError.js';

/**
 * 
 * @export
 * @interface ListComments200ResponseCommentsSubjectsInner
 */
export interface ListComments200ResponseCommentsSubjectsInner {
    /**
     * 
     */
    scope: ListComments200ResponseCommentsSubjectsInnerScopeEnum;
    /**
     * 
     */
    subjectId: string;
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    externalPostId: string | null;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    comments: Array<Comment>;
    /**
     * 
     */
    nextCursor: string | null;
    /**
     * 
     */
    error: GetAnalytics200ResponseAnalyticsSubjectsInnerError | null;
}


/**
 * @export
 */
export const ListComments200ResponseCommentsSubjectsInnerScopeEnum = {
    Destination: 'destination',
    External: 'external',
} as const;
export type ListComments200ResponseCommentsSubjectsInnerScopeEnum = typeof ListComments200ResponseCommentsSubjectsInnerScopeEnum[keyof typeof ListComments200ResponseCommentsSubjectsInnerScopeEnum];


/**
 * Check if a given object implements the ListComments200ResponseCommentsSubjectsInner interface.
 */
export function instanceOfListComments200ResponseCommentsSubjectsInner(value: object): value is ListComments200ResponseCommentsSubjectsInner {
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('subjectId' in value) || value['subjectId'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('externalPostId' in value) || value['externalPostId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ListComments200ResponseCommentsSubjectsInnerFromJSON(json: any): ListComments200ResponseCommentsSubjectsInner {
    return ListComments200ResponseCommentsSubjectsInnerFromJSONTyped(json, false);
}

export function ListComments200ResponseCommentsSubjectsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListComments200ResponseCommentsSubjectsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'],
        'subjectId': json['subjectId'],
        'accountId': json['accountId'],
        'platform': json['platform'],
        'externalPostId': json['externalPostId'],
        'status': json['status'],
        'comments': ((json['comments'] as Array<any>).map(CommentFromJSON)),
        'nextCursor': json['nextCursor'],
        'error': GetAnalytics200ResponseAnalyticsSubjectsInnerErrorFromJSON(json['error']),
    };
}

export function ListComments200ResponseCommentsSubjectsInnerToJSON(json: any): ListComments200ResponseCommentsSubjectsInner {
    return ListComments200ResponseCommentsSubjectsInnerToJSONTyped(json, false);
}

export function ListComments200ResponseCommentsSubjectsInnerToJSONTyped(value?: ListComments200ResponseCommentsSubjectsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'subjectId': value['subjectId'],
        'accountId': value['accountId'],
        'platform': value['platform'],
        'externalPostId': value['externalPostId'],
        'status': value['status'],
        'comments': ((value['comments'] as Array<any>).map(CommentToJSON)),
        'nextCursor': value['nextCursor'],
        'error': GetAnalytics200ResponseAnalyticsSubjectsInnerErrorToJSON(value['error']),
    };
}

