/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListInstagramAccounts200ResponseAccountsInner
 */
export interface ListInstagramAccounts200ResponseAccountsInner {
    /**
     * 
     */
    pageId: string;
    /**
     * 
     */
    pageName: string;
    /**
     * 
     */
    instagramAccountId: string;
    /**
     * 
     */
    username: string;
    /**
     * 
     */
    name: string | null;
    /**
     * 
     */
    profilePictureUrl: string | null;
}

/**
 * Check if a given object implements the ListInstagramAccounts200ResponseAccountsInner interface.
 */
export function instanceOfListInstagramAccounts200ResponseAccountsInner(value: object): value is ListInstagramAccounts200ResponseAccountsInner {
    if (!('pageId' in value) || value['pageId'] === undefined) return false;
    if (!('pageName' in value) || value['pageName'] === undefined) return false;
    if (!('instagramAccountId' in value) || value['instagramAccountId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('profilePictureUrl' in value) || value['profilePictureUrl'] === undefined) return false;
    return true;
}

export function ListInstagramAccounts200ResponseAccountsInnerFromJSON(json: any): ListInstagramAccounts200ResponseAccountsInner {
    return ListInstagramAccounts200ResponseAccountsInnerFromJSONTyped(json, false);
}

export function ListInstagramAccounts200ResponseAccountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInstagramAccounts200ResponseAccountsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'pageId': json['pageId'],
        'pageName': json['pageName'],
        'instagramAccountId': json['instagramAccountId'],
        'username': json['username'],
        'name': json['name'],
        'profilePictureUrl': json['profilePictureUrl'],
    };
}

export function ListInstagramAccounts200ResponseAccountsInnerToJSON(json: any): ListInstagramAccounts200ResponseAccountsInner {
    return ListInstagramAccounts200ResponseAccountsInnerToJSONTyped(json, false);
}

export function ListInstagramAccounts200ResponseAccountsInnerToJSONTyped(value?: ListInstagramAccounts200ResponseAccountsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageId': value['pageId'],
        'pageName': value['pageName'],
        'instagramAccountId': value['instagramAccountId'],
        'username': value['username'],
        'name': value['name'],
        'profilePictureUrl': value['profilePictureUrl'],
    };
}

