/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListRetweeters200ResponseRetweets } from './ListRetweeters200ResponseRetweets.js';
import {
    ListRetweeters200ResponseRetweetsFromJSON,
    ListRetweeters200ResponseRetweetsFromJSONTyped,
    ListRetweeters200ResponseRetweetsToJSON,
    ListRetweeters200ResponseRetweetsToJSONTyped,
} from './ListRetweeters200ResponseRetweets.js';

/**
 * 
 * @export
 * @interface ListRetweeters200Response
 */
export interface ListRetweeters200Response {
    /**
     * 
     */
    retweets: ListRetweeters200ResponseRetweets;
}

/**
 * Check if a given object implements the ListRetweeters200Response interface.
 */
export function instanceOfListRetweeters200Response(value: object): value is ListRetweeters200Response {
    if (!('retweets' in value) || value['retweets'] === undefined) return false;
    return true;
}

export function ListRetweeters200ResponseFromJSON(json: any): ListRetweeters200Response {
    return ListRetweeters200ResponseFromJSONTyped(json, false);
}

export function ListRetweeters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRetweeters200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'retweets': ListRetweeters200ResponseRetweetsFromJSON(json['retweets']),
    };
}

export function ListRetweeters200ResponseToJSON(json: any): ListRetweeters200Response {
    return ListRetweeters200ResponseToJSONTyped(json, false);
}

export function ListRetweeters200ResponseToJSONTyped(value?: ListRetweeters200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'retweets': ListRetweeters200ResponseRetweetsToJSON(value['retweets']),
    };
}

