/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListComments200ResponseComments
 */
export interface ListComments200ResponseComments {
    /**
     * 
     */
    post: string;
    /**
     * 
     */
    subjects: Array<any>;
}

/**
 * Check if a given object implements the ListComments200ResponseComments interface.
 */
export function instanceOfListComments200ResponseComments(value: object): value is ListComments200ResponseComments {
    if (!('post' in value) || value['post'] === undefined) return false;
    if (!('subjects' in value) || value['subjects'] === undefined) return false;
    return true;
}

export function ListComments200ResponseCommentsFromJSON(json: any): ListComments200ResponseComments {
    return ListComments200ResponseCommentsFromJSONTyped(json, false);
}

export function ListComments200ResponseCommentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListComments200ResponseComments {
    if (json == null) {
        return json;
    }
    return {
        
        'post': json['post'],
        'subjects': json['subjects'],
    };
}

export function ListComments200ResponseCommentsToJSON(json: any): ListComments200ResponseComments {
    return ListComments200ResponseCommentsToJSONTyped(json, false);
}

export function ListComments200ResponseCommentsToJSONTyped(value?: ListComments200ResponseComments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': value['post'],
        'subjects': value['subjects'],
    };
}

