/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListConnectionMedia200ResponseItemsInnerMetrics
 */
export interface ListConnectionMedia200ResponseItemsInnerMetrics {
    /**
     * 
     */
    likes: number | null;
    /**
     * 
     */
    comments: number | null;
    /**
     * 
     */
    shares: number | null;
    /**
     * 
     */
    views: number | null;
}

/**
 * Check if a given object implements the ListConnectionMedia200ResponseItemsInnerMetrics interface.
 */
export function instanceOfListConnectionMedia200ResponseItemsInnerMetrics(value: object): value is ListConnectionMedia200ResponseItemsInnerMetrics {
    if (!('likes' in value) || value['likes'] === undefined) return false;
    if (!('comments' in value) || value['comments'] === undefined) return false;
    if (!('shares' in value) || value['shares'] === undefined) return false;
    if (!('views' in value) || value['views'] === undefined) return false;
    return true;
}

export function ListConnectionMedia200ResponseItemsInnerMetricsFromJSON(json: any): ListConnectionMedia200ResponseItemsInnerMetrics {
    return ListConnectionMedia200ResponseItemsInnerMetricsFromJSONTyped(json, false);
}

export function ListConnectionMedia200ResponseItemsInnerMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectionMedia200ResponseItemsInnerMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'likes': json['likes'],
        'comments': json['comments'],
        'shares': json['shares'],
        'views': json['views'],
    };
}

export function ListConnectionMedia200ResponseItemsInnerMetricsToJSON(json: any): ListConnectionMedia200ResponseItemsInnerMetrics {
    return ListConnectionMedia200ResponseItemsInnerMetricsToJSONTyped(json, false);
}

export function ListConnectionMedia200ResponseItemsInnerMetricsToJSONTyped(value?: ListConnectionMedia200ResponseItemsInnerMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'likes': value['likes'],
        'comments': value['comments'],
        'shares': value['shares'],
        'views': value['views'],
    };
}

