/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ListProfiles403ResponseError
 */
export interface ListProfiles403ResponseError {
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    message: string;
}

/**
 * Check if a given object implements the ListProfiles403ResponseError interface.
 */
export function instanceOfListProfiles403ResponseError(value: object): value is ListProfiles403ResponseError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ListProfiles403ResponseErrorFromJSON(json: any): ListProfiles403ResponseError {
    return ListProfiles403ResponseErrorFromJSONTyped(json, false);
}

export function ListProfiles403ResponseErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProfiles403ResponseError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function ListProfiles403ResponseErrorToJSON(json: any): ListProfiles403ResponseError {
    return ListProfiles403ResponseErrorToJSONTyped(json, false);
}

export function ListProfiles403ResponseErrorToJSONTyped(value?: ListProfiles403ResponseError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

