/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MediaAsset } from './MediaAsset.js';
import {
    MediaAssetFromJSON,
    MediaAssetFromJSONTyped,
    MediaAssetToJSON,
    MediaAssetToJSONTyped,
} from './MediaAsset.js';

/**
 * 
 * @export
 * @interface ListMedia200Response
 */
export interface ListMedia200Response {
    /**
     * 
     */
    media: Array<MediaAsset>;
    /**
     * Total media assets, across every page.
     */
    total: number;
    /**
     * The 1-based page this response carries.
     */
    page: number;
    /**
     * True when at least one more asset follows this page. Request `page + 1` while it is true.
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the ListMedia200Response interface.
 */
export function instanceOfListMedia200Response(value: object): value is ListMedia200Response {
    if (!('media' in value) || value['media'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function ListMedia200ResponseFromJSON(json: any): ListMedia200Response {
    return ListMedia200ResponseFromJSONTyped(json, false);
}

export function ListMedia200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMedia200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'media': ((json['media'] as Array<any>).map(MediaAssetFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'hasMore': json['hasMore'],
    };
}

export function ListMedia200ResponseToJSON(json: any): ListMedia200Response {
    return ListMedia200ResponseToJSONTyped(json, false);
}

export function ListMedia200ResponseToJSONTyped(value?: ListMedia200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media': ((value['media'] as Array<any>).map(MediaAssetToJSON)),
        'total': value['total'],
        'page': value['page'],
        'hasMore': value['hasMore'],
    };
}

