/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListPosts200ResponseFacetsStatusInner } from './ListPosts200ResponseFacetsStatusInner.js';
import {
    ListPosts200ResponseFacetsStatusInnerFromJSON,
    ListPosts200ResponseFacetsStatusInnerFromJSONTyped,
    ListPosts200ResponseFacetsStatusInnerToJSON,
    ListPosts200ResponseFacetsStatusInnerToJSONTyped,
} from './ListPosts200ResponseFacetsStatusInner.js';
import type { ListPosts200ResponseFacetsPlatformInner } from './ListPosts200ResponseFacetsPlatformInner.js';
import {
    ListPosts200ResponseFacetsPlatformInnerFromJSON,
    ListPosts200ResponseFacetsPlatformInnerFromJSONTyped,
    ListPosts200ResponseFacetsPlatformInnerToJSON,
    ListPosts200ResponseFacetsPlatformInnerToJSONTyped,
} from './ListPosts200ResponseFacetsPlatformInner.js';

/**
 * 
 * @export
 * @interface ListPosts200ResponseFacets
 */
export interface ListPosts200ResponseFacets {
    /**
     * 
     */
    status: Array<ListPosts200ResponseFacetsStatusInner>;
    /**
     * 
     */
    platform: Array<ListPosts200ResponseFacetsPlatformInner>;
}

/**
 * Check if a given object implements the ListPosts200ResponseFacets interface.
 */
export function instanceOfListPosts200ResponseFacets(value: object): value is ListPosts200ResponseFacets {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function ListPosts200ResponseFacetsFromJSON(json: any): ListPosts200ResponseFacets {
    return ListPosts200ResponseFacetsFromJSONTyped(json, false);
}

export function ListPosts200ResponseFacetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPosts200ResponseFacets {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ((json['status'] as Array<any>).map(ListPosts200ResponseFacetsStatusInnerFromJSON)),
        'platform': ((json['platform'] as Array<any>).map(ListPosts200ResponseFacetsPlatformInnerFromJSON)),
    };
}

export function ListPosts200ResponseFacetsToJSON(json: any): ListPosts200ResponseFacets {
    return ListPosts200ResponseFacetsToJSONTyped(json, false);
}

export function ListPosts200ResponseFacetsToJSONTyped(value?: ListPosts200ResponseFacets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ((value['status'] as Array<any>).map(ListPosts200ResponseFacetsStatusInnerToJSON)),
        'platform': ((value['platform'] as Array<any>).map(ListPosts200ResponseFacetsPlatformInnerToJSON)),
    };
}

