/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface NormalizedMetrics
 */
export interface NormalizedMetrics {
    /**
     * 
     */
    impressions?: number | null;
    /**
     * 
     */
    reach?: number | null;
    /**
     * 
     */
    likes?: number | null;
    /**
     * 
     */
    comments?: number | null;
    /**
     * 
     */
    shares?: number | null;
    /**
     * 
     */
    saves?: number | null;
    /**
     * 
     */
    plays?: number | null;
    /**
     * 
     */
    engagement?: number | null;
}

/**
 * Check if a given object implements the NormalizedMetrics interface.
 */
export function instanceOfNormalizedMetrics(value: object): value is NormalizedMetrics {
    return true;
}

export function NormalizedMetricsFromJSON(json: any): NormalizedMetrics {
    return NormalizedMetricsFromJSONTyped(json, false);
}

export function NormalizedMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NormalizedMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'impressions': json['impressions'] === undefined ? undefined : json['impressions'] === null ? null : json['impressions'],
        'reach': json['reach'] === undefined ? undefined : json['reach'] === null ? null : json['reach'],
        'likes': json['likes'] === undefined ? undefined : json['likes'] === null ? null : json['likes'],
        'comments': json['comments'] === undefined ? undefined : json['comments'] === null ? null : json['comments'],
        'shares': json['shares'] === undefined ? undefined : json['shares'] === null ? null : json['shares'],
        'saves': json['saves'] === undefined ? undefined : json['saves'] === null ? null : json['saves'],
        'plays': json['plays'] === undefined ? undefined : json['plays'] === null ? null : json['plays'],
        'engagement': json['engagement'] === undefined ? undefined : json['engagement'] === null ? null : json['engagement'],
    };
}

export function NormalizedMetricsToJSON(json: any): NormalizedMetrics {
    return NormalizedMetricsToJSONTyped(json, false);
}

export function NormalizedMetricsToJSONTyped(value?: NormalizedMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'impressions': value['impressions'],
        'reach': value['reach'],
        'likes': value['likes'],
        'comments': value['comments'],
        'shares': value['shares'],
        'saves': value['saves'],
        'plays': value['plays'],
        'engagement': value['engagement'],
    };
}

