/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { PostDestination } from './PostDestination.js';
import {
    PostDestinationFromJSON,
    PostDestinationFromJSONTyped,
    PostDestinationToJSON,
    PostDestinationToJSONTyped,
} from './PostDestination.js';
import type { MediaKind } from './MediaKind.js';
import {
    MediaKindFromJSON,
    MediaKindFromJSONTyped,
    MediaKindToJSON,
    MediaKindToJSONTyped,
} from './MediaKind.js';
import type { PostStatus } from './PostStatus.js';
import {
    PostStatusFromJSON,
    PostStatusFromJSONTyped,
    PostStatusToJSON,
    PostStatusToJSONTyped,
} from './PostStatus.js';

/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    mediaUrls: Array<string>;
    /**
     * 
     */
    mediaKind: MediaKind;
    /**
     * 
     */
    status: PostStatus;
    /**
     * Timezone-naive local datetime in `timezone` (e.g. 2026-07-16T12:00:00).
     */
    scheduledFor: string | null;
    /**
     * IANA timezone for `scheduledFor`.
     */
    timezone: string | null;
    /**
     * 
     */
    destinations: Array<PostDestination>;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): value is Post {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('mediaUrls' in value) || value['mediaUrls'] === undefined) return false;
    if (!('mediaKind' in value) || value['mediaKind'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('scheduledFor' in value) || value['scheduledFor'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('destinations' in value) || value['destinations'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PostFromJSON(json: any): Post {
    return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': json['text'],
        'mediaUrls': json['mediaUrls'],
        'mediaKind': MediaKindFromJSON(json['mediaKind']),
        'status': PostStatusFromJSON(json['status']),
        'scheduledFor': json['scheduledFor'],
        'timezone': json['timezone'],
        'destinations': ((json['destinations'] as Array<any>).map(PostDestinationFromJSON)),
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function PostToJSON(json: any): Post {
    return PostToJSONTyped(json, false);
}

export function PostToJSONTyped(value?: Post | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'mediaUrls': value['mediaUrls'],
        'mediaKind': MediaKindToJSON(value['mediaKind']),
        'status': PostStatusToJSON(value['status']),
        'scheduledFor': value['scheduledFor'],
        'timezone': value['timezone'],
        'destinations': ((value['destinations'] as Array<any>).map(PostDestinationToJSON)),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

