/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
import type { DestinationStatus } from './DestinationStatus.js';
import {
    DestinationStatusFromJSON,
    DestinationStatusFromJSONTyped,
    DestinationStatusToJSON,
    DestinationStatusToJSONTyped,
} from './DestinationStatus.js';

/**
 * 
 * @export
 * @interface PostDestination
 */
export interface PostDestination {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    connectionId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    status: DestinationStatus;
    /**
     * 
     */
    externalPostId: string | null;
    /**
     * 
     */
    externalUrl: string | null;
    /**
     * 
     */
    errorCode: string | null;
    /**
     * 
     */
    errorMessage: string | null;
    /**
     * 
     */
    publishedAt: Date | null;
}



/**
 * Check if a given object implements the PostDestination interface.
 */
export function instanceOfPostDestination(value: object): value is PostDestination {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('externalPostId' in value) || value['externalPostId'] === undefined) return false;
    if (!('externalUrl' in value) || value['externalUrl'] === undefined) return false;
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    return true;
}

export function PostDestinationFromJSON(json: any): PostDestination {
    return PostDestinationFromJSONTyped(json, false);
}

export function PostDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDestination {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'connectionId': json['connectionId'],
        'platform': json['platform'],
        'status': DestinationStatusFromJSON(json['status']),
        'externalPostId': json['externalPostId'],
        'externalUrl': json['externalUrl'],
        'errorCode': json['errorCode'],
        'errorMessage': json['errorMessage'],
        'publishedAt': (json['publishedAt'] == null ? null : parseDateTime(json['publishedAt'])),
    };
}

export function PostDestinationToJSON(json: any): PostDestination {
    return PostDestinationToJSONTyped(json, false);
}

export function PostDestinationToJSONTyped(value?: PostDestination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'connectionId': value['connectionId'],
        'platform': value['platform'],
        'status': DestinationStatusToJSON(value['status']),
        'externalPostId': value['externalPostId'],
        'externalUrl': value['externalUrl'],
        'errorCode': value['errorCode'],
        'errorMessage': value['errorMessage'],
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : serializeDateTime(value['publishedAt']),
    };
}

