/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PresignMediaBody
 */
export interface PresignMediaBody {
    /**
     * 
     */
    filename: string;
    /**
     * 
     */
    contentType: string;
}

/**
 * Check if a given object implements the PresignMediaBody interface.
 */
export function instanceOfPresignMediaBody(value: object): value is PresignMediaBody {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    return true;
}

export function PresignMediaBodyFromJSON(json: any): PresignMediaBody {
    return PresignMediaBodyFromJSONTyped(json, false);
}

export function PresignMediaBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignMediaBody {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'contentType': json['contentType'],
    };
}

export function PresignMediaBodyToJSON(json: any): PresignMediaBody {
    return PresignMediaBodyToJSONTyped(json, false);
}

export function PresignMediaBodyToJSONTyped(value?: PresignMediaBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'contentType': value['contentType'],
    };
}

