/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PresignedUpload
 */
export interface PresignedUpload {
    /**
     * 
     */
    uploadUrl: string;
    /**
     * 
     */
    publicUrl: string;
    /**
     * 
     */
    key: string;
    /**
     * 
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the PresignedUpload interface.
 */
export function instanceOfPresignedUpload(value: object): value is PresignedUpload {
    if (!('uploadUrl' in value) || value['uploadUrl'] === undefined) return false;
    if (!('publicUrl' in value) || value['publicUrl'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function PresignedUploadFromJSON(json: any): PresignedUpload {
    return PresignedUploadFromJSONTyped(json, false);
}

export function PresignedUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignedUpload {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadUrl': json['uploadUrl'],
        'publicUrl': json['publicUrl'],
        'key': json['key'],
        'expiresIn': json['expiresIn'],
    };
}

export function PresignedUploadToJSON(json: any): PresignedUpload {
    return PresignedUploadToJSONTyped(json, false);
}

export function PresignedUploadToJSONTyped(value?: PresignedUpload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploadUrl': value['uploadUrl'],
        'publicUrl': value['publicUrl'],
        'key': value['key'],
        'expiresIn': value['expiresIn'],
    };
}

