/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Quote201Response
 */
export interface Quote201Response {
    /**
     * 
     */
    quote?: any | null;
}

/**
 * Check if a given object implements the Quote201Response interface.
 */
export function instanceOfQuote201Response(value: object): value is Quote201Response {
    return true;
}

export function Quote201ResponseFromJSON(json: any): Quote201Response {
    return Quote201ResponseFromJSONTyped(json, false);
}

export function Quote201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quote201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'quote': json['quote'] === undefined ? undefined : json['quote'] === null ? null : json['quote'],
    };
}

export function Quote201ResponseToJSON(json: any): Quote201Response {
    return Quote201ResponseToJSONTyped(json, false);
}

export function Quote201ResponseToJSONTyped(value?: Quote201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quote': value['quote'],
    };
}

