/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface QuoteBody
 */
export interface QuoteBody {
    /**
     * 
     */
    destinationId: string;
    /**
     * 
     */
    text: string;
}

/**
 * Check if a given object implements the QuoteBody interface.
 */
export function instanceOfQuoteBody(value: object): value is QuoteBody {
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function QuoteBodyFromJSON(json: any): QuoteBody {
    return QuoteBodyFromJSONTyped(json, false);
}

export function QuoteBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuoteBody {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationId': json['destinationId'],
        'text': json['text'],
    };
}

export function QuoteBodyToJSON(json: any): QuoteBody {
    return QuoteBodyToJSONTyped(json, false);
}

export function QuoteBodyToJSONTyped(value?: QuoteBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationId': value['destinationId'],
        'text': value['text'],
    };
}

