/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SetMessengerProfileBodyPersistentMenuInner } from './SetMessengerProfileBodyPersistentMenuInner.js';
import {
    SetMessengerProfileBodyPersistentMenuInnerFromJSON,
    SetMessengerProfileBodyPersistentMenuInnerFromJSONTyped,
    SetMessengerProfileBodyPersistentMenuInnerToJSON,
    SetMessengerProfileBodyPersistentMenuInnerToJSONTyped,
} from './SetMessengerProfileBodyPersistentMenuInner.js';
import type { SendInboxMessageBodyQuickRepliesInner } from './SendInboxMessageBodyQuickRepliesInner.js';
import {
    SendInboxMessageBodyQuickRepliesInnerFromJSON,
    SendInboxMessageBodyQuickRepliesInnerFromJSONTyped,
    SendInboxMessageBodyQuickRepliesInnerToJSON,
    SendInboxMessageBodyQuickRepliesInnerToJSONTyped,
} from './SendInboxMessageBodyQuickRepliesInner.js';
import type { SendInboxMessageBodyTemplateElementsInner } from './SendInboxMessageBodyTemplateElementsInner.js';
import {
    SendInboxMessageBodyTemplateElementsInnerFromJSON,
    SendInboxMessageBodyTemplateElementsInnerFromJSONTyped,
    SendInboxMessageBodyTemplateElementsInnerToJSON,
    SendInboxMessageBodyTemplateElementsInnerToJSONTyped,
} from './SendInboxMessageBodyTemplateElementsInner.js';

/**
 * 
 * @export
 * @interface SendInboxMessageBody
 */
export interface SendInboxMessageBody {
    /**
     * Connection id.
     */
    accountId: string;
    /**
     * 
     */
    convoId: string;
    /**
     * 
     */
    text: string;
    /**
     * Instagram and Facebook only. Public HTTPS media URL sent as an attachment (image, video, audio, PDF).
     */
    attachmentUrl?: string;
    /**
     * Instagram and Facebook only. Quick reply buttons (max 13).
     */
    quickReplies?: Array<SendInboxMessageBodyQuickRepliesInner>;
    /**
     * Instagram and Facebook only. Button template buttons (max 3).
     */
    buttons?: Array<SetMessengerProfileBodyPersistentMenuInner>;
    /**
     * Instagram and Facebook only. Generic carousel elements (max 10).
     */
    templateElements?: Array<SendInboxMessageBodyTemplateElementsInner>;
}

/**
 * Check if a given object implements the SendInboxMessageBody interface.
 */
export function instanceOfSendInboxMessageBody(value: object): value is SendInboxMessageBody {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('convoId' in value) || value['convoId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SendInboxMessageBodyFromJSON(json: any): SendInboxMessageBody {
    return SendInboxMessageBodyFromJSONTyped(json, false);
}

export function SendInboxMessageBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendInboxMessageBody {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'convoId': json['convoId'],
        'text': json['text'],
        'attachmentUrl': json['attachmentUrl'] == null ? undefined : json['attachmentUrl'],
        'quickReplies': json['quickReplies'] == null ? undefined : ((json['quickReplies'] as Array<any>).map(SendInboxMessageBodyQuickRepliesInnerFromJSON)),
        'buttons': json['buttons'] == null ? undefined : ((json['buttons'] as Array<any>).map(SetMessengerProfileBodyPersistentMenuInnerFromJSON)),
        'templateElements': json['templateElements'] == null ? undefined : ((json['templateElements'] as Array<any>).map(SendInboxMessageBodyTemplateElementsInnerFromJSON)),
    };
}

export function SendInboxMessageBodyToJSON(json: any): SendInboxMessageBody {
    return SendInboxMessageBodyToJSONTyped(json, false);
}

export function SendInboxMessageBodyToJSONTyped(value?: SendInboxMessageBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'convoId': value['convoId'],
        'text': value['text'],
        'attachmentUrl': value['attachmentUrl'],
        'quickReplies': value['quickReplies'] == null ? undefined : ((value['quickReplies'] as Array<any>).map(SendInboxMessageBodyQuickRepliesInnerToJSON)),
        'buttons': value['buttons'] == null ? undefined : ((value['buttons'] as Array<any>).map(SetMessengerProfileBodyPersistentMenuInnerToJSON)),
        'templateElements': value['templateElements'] == null ? undefined : ((value['templateElements'] as Array<any>).map(SendInboxMessageBodyTemplateElementsInnerToJSON)),
    };
}

