/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ListInboxMessages200ResponseMessagesInner } from './ListInboxMessages200ResponseMessagesInner.js';
import {
    ListInboxMessages200ResponseMessagesInnerFromJSON,
    ListInboxMessages200ResponseMessagesInnerFromJSONTyped,
    ListInboxMessages200ResponseMessagesInnerToJSON,
    ListInboxMessages200ResponseMessagesInnerToJSONTyped,
} from './ListInboxMessages200ResponseMessagesInner.js';

/**
 * 
 * @export
 * @interface SendInboxMessage201Response
 */
export interface SendInboxMessage201Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    message: ListInboxMessages200ResponseMessagesInner;
}

/**
 * Check if a given object implements the SendInboxMessage201Response interface.
 */
export function instanceOfSendInboxMessage201Response(value: object): value is SendInboxMessage201Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SendInboxMessage201ResponseFromJSON(json: any): SendInboxMessage201Response {
    return SendInboxMessage201ResponseFromJSONTyped(json, false);
}

export function SendInboxMessage201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendInboxMessage201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'message': ListInboxMessages200ResponseMessagesInnerFromJSON(json['message']),
    };
}

export function SendInboxMessage201ResponseToJSON(json: any): SendInboxMessage201Response {
    return SendInboxMessage201ResponseToJSONTyped(json, false);
}

export function SendInboxMessage201ResponseToJSONTyped(value?: SendInboxMessage201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'message': ListInboxMessages200ResponseMessagesInnerToJSON(value['message']),
    };
}

