/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SendInboxMessageBodyQuickRepliesInner
 */
export interface SendInboxMessageBodyQuickRepliesInner {
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    payload: string;
    /**
     * 
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the SendInboxMessageBodyQuickRepliesInner interface.
 */
export function instanceOfSendInboxMessageBodyQuickRepliesInner(value: object): value is SendInboxMessageBodyQuickRepliesInner {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function SendInboxMessageBodyQuickRepliesInnerFromJSON(json: any): SendInboxMessageBodyQuickRepliesInner {
    return SendInboxMessageBodyQuickRepliesInnerFromJSONTyped(json, false);
}

export function SendInboxMessageBodyQuickRepliesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendInboxMessageBodyQuickRepliesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'payload': json['payload'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function SendInboxMessageBodyQuickRepliesInnerToJSON(json: any): SendInboxMessageBodyQuickRepliesInner {
    return SendInboxMessageBodyQuickRepliesInnerToJSONTyped(json, false);
}

export function SendInboxMessageBodyQuickRepliesInnerToJSONTyped(value?: SendInboxMessageBodyQuickRepliesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'payload': value['payload'],
        'imageUrl': value['imageUrl'],
    };
}

