/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner
 */
export interface SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner {
    /**
     * 
     */
    type: string;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    url: string | null;
    /**
     * 
     */
    payload: string | null;
}

/**
 * Check if a given object implements the SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner interface.
 */
export function instanceOfSetConnectionMessengerProfile200ResponseProfilePersistentMenuInner(value: object): value is SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerFromJSON(json: any): SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner {
    return SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerFromJSONTyped(json, false);
}

export function SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'url': json['url'],
        'payload': json['payload'],
    };
}

export function SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerToJSON(json: any): SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner {
    return SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerToJSONTyped(json, false);
}

export function SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerToJSONTyped(value?: SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'url': value['url'],
        'payload': value['payload'],
    };
}

