/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SetConnectionMessengerProfile200ResponseProfile } from './SetConnectionMessengerProfile200ResponseProfile.js';
import {
    SetConnectionMessengerProfile200ResponseProfileFromJSON,
    SetConnectionMessengerProfile200ResponseProfileFromJSONTyped,
    SetConnectionMessengerProfile200ResponseProfileToJSON,
    SetConnectionMessengerProfile200ResponseProfileToJSONTyped,
} from './SetConnectionMessengerProfile200ResponseProfile.js';

/**
 * 
 * @export
 * @interface SetConnectionMessengerProfile200Response
 */
export interface SetConnectionMessengerProfile200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    profile: SetConnectionMessengerProfile200ResponseProfile;
}

/**
 * Check if a given object implements the SetConnectionMessengerProfile200Response interface.
 */
export function instanceOfSetConnectionMessengerProfile200Response(value: object): value is SetConnectionMessengerProfile200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function SetConnectionMessengerProfile200ResponseFromJSON(json: any): SetConnectionMessengerProfile200Response {
    return SetConnectionMessengerProfile200ResponseFromJSONTyped(json, false);
}

export function SetConnectionMessengerProfile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetConnectionMessengerProfile200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'profile': SetConnectionMessengerProfile200ResponseProfileFromJSON(json['profile']),
    };
}

export function SetConnectionMessengerProfile200ResponseToJSON(json: any): SetConnectionMessengerProfile200Response {
    return SetConnectionMessengerProfile200ResponseToJSONTyped(json, false);
}

export function SetConnectionMessengerProfile200ResponseToJSONTyped(value?: SetConnectionMessengerProfile200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'profile': SetConnectionMessengerProfile200ResponseProfileToJSON(value['profile']),
    };
}

