/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner } from './SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner.js';
import {
    SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerFromJSON,
    SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerFromJSONTyped,
    SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerToJSON,
    SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerToJSONTyped,
} from './SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner.js';
import type { SetConnectionMessengerProfile200ResponseProfileIceBreakersInner } from './SetConnectionMessengerProfile200ResponseProfileIceBreakersInner.js';
import {
    SetConnectionMessengerProfile200ResponseProfileIceBreakersInnerFromJSON,
    SetConnectionMessengerProfile200ResponseProfileIceBreakersInnerFromJSONTyped,
    SetConnectionMessengerProfile200ResponseProfileIceBreakersInnerToJSON,
    SetConnectionMessengerProfile200ResponseProfileIceBreakersInnerToJSONTyped,
} from './SetConnectionMessengerProfile200ResponseProfileIceBreakersInner.js';

/**
 * 
 * @export
 * @interface SetConnectionMessengerProfile200ResponseProfile
 */
export interface SetConnectionMessengerProfile200ResponseProfile {
    /**
     * 
     */
    iceBreakers: Array<SetConnectionMessengerProfile200ResponseProfileIceBreakersInner>;
    /**
     * 
     */
    persistentMenu: Array<SetConnectionMessengerProfile200ResponseProfilePersistentMenuInner>;
}

/**
 * Check if a given object implements the SetConnectionMessengerProfile200ResponseProfile interface.
 */
export function instanceOfSetConnectionMessengerProfile200ResponseProfile(value: object): value is SetConnectionMessengerProfile200ResponseProfile {
    if (!('iceBreakers' in value) || value['iceBreakers'] === undefined) return false;
    if (!('persistentMenu' in value) || value['persistentMenu'] === undefined) return false;
    return true;
}

export function SetConnectionMessengerProfile200ResponseProfileFromJSON(json: any): SetConnectionMessengerProfile200ResponseProfile {
    return SetConnectionMessengerProfile200ResponseProfileFromJSONTyped(json, false);
}

export function SetConnectionMessengerProfile200ResponseProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetConnectionMessengerProfile200ResponseProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'iceBreakers': ((json['iceBreakers'] as Array<any>).map(SetConnectionMessengerProfile200ResponseProfileIceBreakersInnerFromJSON)),
        'persistentMenu': ((json['persistentMenu'] as Array<any>).map(SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerFromJSON)),
    };
}

export function SetConnectionMessengerProfile200ResponseProfileToJSON(json: any): SetConnectionMessengerProfile200ResponseProfile {
    return SetConnectionMessengerProfile200ResponseProfileToJSONTyped(json, false);
}

export function SetConnectionMessengerProfile200ResponseProfileToJSONTyped(value?: SetConnectionMessengerProfile200ResponseProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iceBreakers': ((value['iceBreakers'] as Array<any>).map(SetConnectionMessengerProfile200ResponseProfileIceBreakersInnerToJSON)),
        'persistentMenu': ((value['persistentMenu'] as Array<any>).map(SetConnectionMessengerProfile200ResponseProfilePersistentMenuInnerToJSON)),
    };
}

