/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SetMessengerProfileBodyPersistentMenuInner
 */
export interface SetMessengerProfileBodyPersistentMenuInner {
    /**
     * 
     */
    type: SetMessengerProfileBodyPersistentMenuInnerTypeEnum;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    url?: string;
    /**
     * 
     */
    payload?: string;
}


/**
 * @export
 */
export const SetMessengerProfileBodyPersistentMenuInnerTypeEnum = {
    WebUrl: 'web_url',
    Postback: 'postback',
} as const;
export type SetMessengerProfileBodyPersistentMenuInnerTypeEnum = typeof SetMessengerProfileBodyPersistentMenuInnerTypeEnum[keyof typeof SetMessengerProfileBodyPersistentMenuInnerTypeEnum];


/**
 * Check if a given object implements the SetMessengerProfileBodyPersistentMenuInner interface.
 */
export function instanceOfSetMessengerProfileBodyPersistentMenuInner(value: object): value is SetMessengerProfileBodyPersistentMenuInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function SetMessengerProfileBodyPersistentMenuInnerFromJSON(json: any): SetMessengerProfileBodyPersistentMenuInner {
    return SetMessengerProfileBodyPersistentMenuInnerFromJSONTyped(json, false);
}

export function SetMessengerProfileBodyPersistentMenuInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetMessengerProfileBodyPersistentMenuInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'url': json['url'] == null ? undefined : json['url'],
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function SetMessengerProfileBodyPersistentMenuInnerToJSON(json: any): SetMessengerProfileBodyPersistentMenuInner {
    return SetMessengerProfileBodyPersistentMenuInnerToJSONTyped(json, false);
}

export function SetMessengerProfileBodyPersistentMenuInnerToJSONTyped(value?: SetMessengerProfileBodyPersistentMenuInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'url': value['url'],
        'payload': value['payload'],
    };
}

