/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ExternalPost } from './ExternalPost.js';
import {
    ExternalPostFromJSON,
    ExternalPostFromJSONTyped,
    ExternalPostToJSON,
    ExternalPostToJSONTyped,
} from './ExternalPost.js';
import type { SyncExternal200ResponseSynced } from './SyncExternal200ResponseSynced.js';
import {
    SyncExternal200ResponseSyncedFromJSON,
    SyncExternal200ResponseSyncedFromJSONTyped,
    SyncExternal200ResponseSyncedToJSON,
    SyncExternal200ResponseSyncedToJSONTyped,
} from './SyncExternal200ResponseSynced.js';

/**
 * 
 * @export
 * @interface SyncExternal200Response
 */
export interface SyncExternal200Response {
    /**
     * 
     */
    synced: SyncExternal200ResponseSynced;
    /**
     * 
     */
    found?: boolean;
    /**
     * 
     */
    post?: ExternalPost | null;
    /**
     * 
     */
    posts?: Array<ExternalPost>;
}

/**
 * Check if a given object implements the SyncExternal200Response interface.
 */
export function instanceOfSyncExternal200Response(value: object): value is SyncExternal200Response {
    if (!('synced' in value) || value['synced'] === undefined) return false;
    return true;
}

export function SyncExternal200ResponseFromJSON(json: any): SyncExternal200Response {
    return SyncExternal200ResponseFromJSONTyped(json, false);
}

export function SyncExternal200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncExternal200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'synced': SyncExternal200ResponseSyncedFromJSON(json['synced']),
        'found': json['found'] == null ? undefined : json['found'],
        'post': json['post'] === undefined ? undefined : json['post'] === null ? null : ExternalPostFromJSON(json['post']),
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(ExternalPostFromJSON)),
    };
}

export function SyncExternal200ResponseToJSON(json: any): SyncExternal200Response {
    return SyncExternal200ResponseToJSONTyped(json, false);
}

export function SyncExternal200ResponseToJSONTyped(value?: SyncExternal200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'synced': SyncExternal200ResponseSyncedToJSON(value['synced']),
        'found': value['found'],
        'post': ExternalPostToJSON(value['post']),
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(ExternalPostToJSON)),
    };
}

