/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SyncExternal200ResponseSynced
 */
export interface SyncExternal200ResponseSynced {
    /**
     * 
     */
    postsFound: number;
    /**
     * 
     */
    postsSynced: number;
    /**
     * 
     */
    skipped: boolean;
}

/**
 * Check if a given object implements the SyncExternal200ResponseSynced interface.
 */
export function instanceOfSyncExternal200ResponseSynced(value: object): value is SyncExternal200ResponseSynced {
    if (!('postsFound' in value) || value['postsFound'] === undefined) return false;
    if (!('postsSynced' in value) || value['postsSynced'] === undefined) return false;
    if (!('skipped' in value) || value['skipped'] === undefined) return false;
    return true;
}

export function SyncExternal200ResponseSyncedFromJSON(json: any): SyncExternal200ResponseSynced {
    return SyncExternal200ResponseSyncedFromJSONTyped(json, false);
}

export function SyncExternal200ResponseSyncedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncExternal200ResponseSynced {
    if (json == null) {
        return json;
    }
    return {
        
        'postsFound': json['postsFound'],
        'postsSynced': json['postsSynced'],
        'skipped': json['skipped'],
    };
}

export function SyncExternal200ResponseSyncedToJSON(json: any): SyncExternal200ResponseSynced {
    return SyncExternal200ResponseSyncedToJSONTyped(json, false);
}

export function SyncExternal200ResponseSyncedToJSONTyped(value?: SyncExternal200ResponseSynced | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postsFound': value['postsFound'],
        'postsSynced': value['postsSynced'],
        'skipped': value['skipped'],
    };
}

