/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SyncExternalBody
 */
export interface SyncExternalBody {
    /**
     * Connected social account id whose posts to sync.
     */
    accountId: string;
    /**
     * Post URL to locate. Optional: provide url or postId for single-post mode, omit both for bulk refresh.
     */
    url?: string;
    /**
     * Platform-native post/media/video id to locate, as an alternative to url.
     */
    postId?: string;
}

/**
 * Check if a given object implements the SyncExternalBody interface.
 */
export function instanceOfSyncExternalBody(value: object): value is SyncExternalBody {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    return true;
}

export function SyncExternalBodyFromJSON(json: any): SyncExternalBody {
    return SyncExternalBodyFromJSONTyped(json, false);
}

export function SyncExternalBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncExternalBody {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'url': json['url'] == null ? undefined : json['url'],
        'postId': json['postId'] == null ? undefined : json['postId'],
    };
}

export function SyncExternalBodyToJSON(json: any): SyncExternalBody {
    return SyncExternalBodyToJSONTyped(json, false);
}

export function SyncExternalBodyToJSONTyped(value?: SyncExternalBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'url': value['url'],
        'postId': value['postId'],
    };
}

