/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ThreadItem
 */
export interface ThreadItem {
    /**
     * 
     */
    content?: string;
    /**
     * 
     */
    mediaItems?: Array<string>;
}

/**
 * Check if a given object implements the ThreadItem interface.
 */
export function instanceOfThreadItem(value: object): value is ThreadItem {
    return true;
}

export function ThreadItemFromJSON(json: any): ThreadItem {
    return ThreadItemFromJSONTyped(json, false);
}

export function ThreadItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadItem {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'mediaItems': json['mediaItems'] == null ? undefined : json['mediaItems'],
    };
}

export function ThreadItemToJSON(json: any): ThreadItem {
    return ThreadItemToJSONTyped(json, false);
}

export function ThreadItemToJSONTyped(value?: ThreadItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'mediaItems': value['mediaItems'],
    };
}

