/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UndoRetweet200Response
 */
export interface UndoRetweet200Response {
    /**
     * 
     */
    postId: string;
    /**
     * 
     */
    destinationId: string;
    /**
     * 
     */
    platform: string;
    /**
     * 
     */
    retweeted: boolean;
}

/**
 * Check if a given object implements the UndoRetweet200Response interface.
 */
export function instanceOfUndoRetweet200Response(value: object): value is UndoRetweet200Response {
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('destinationId' in value) || value['destinationId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('retweeted' in value) || value['retweeted'] === undefined) return false;
    return true;
}

export function UndoRetweet200ResponseFromJSON(json: any): UndoRetweet200Response {
    return UndoRetweet200ResponseFromJSONTyped(json, false);
}

export function UndoRetweet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UndoRetweet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'postId': json['postId'],
        'destinationId': json['destinationId'],
        'platform': json['platform'],
        'retweeted': json['retweeted'],
    };
}

export function UndoRetweet200ResponseToJSON(json: any): UndoRetweet200Response {
    return UndoRetweet200ResponseToJSONTyped(json, false);
}

export function UndoRetweet200ResponseToJSONTyped(value?: UndoRetweet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postId': value['postId'],
        'destinationId': value['destinationId'],
        'platform': value['platform'],
        'retweeted': value['retweeted'],
    };
}

