/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateBlueskySettings200Response
 */
export interface UpdateBlueskySettings200Response {
    /**
     * 
     */
    accountId: string;
    /**
     * 
     */
    platform: UpdateBlueskySettings200ResponsePlatformEnum;
    /**
     * 
     */
    defaultLangs: Array<string> | null;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const UpdateBlueskySettings200ResponsePlatformEnum = {
    Bluesky: 'bluesky',
} as const;
export type UpdateBlueskySettings200ResponsePlatformEnum = typeof UpdateBlueskySettings200ResponsePlatformEnum[keyof typeof UpdateBlueskySettings200ResponsePlatformEnum];


/**
 * Check if a given object implements the UpdateBlueskySettings200Response interface.
 */
export function instanceOfUpdateBlueskySettings200Response(value: object): value is UpdateBlueskySettings200Response {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (value['platform'] !== 'bluesky') return false;
    
    if (!('defaultLangs' in value) || value['defaultLangs'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UpdateBlueskySettings200ResponseFromJSON(json: any): UpdateBlueskySettings200Response {
    return UpdateBlueskySettings200ResponseFromJSONTyped(json, false);
}

export function UpdateBlueskySettings200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBlueskySettings200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'platform': json['platform'],
        'defaultLangs': json['defaultLangs'] == null ? null : json['defaultLangs'],
        'updatedAt': (json['updatedAt'] == null ? json['updatedAt'] : parseDateTime(json['updatedAt'])),
    };
}

export function UpdateBlueskySettings200ResponseToJSON(json: any): UpdateBlueskySettings200Response {
    return UpdateBlueskySettings200ResponseToJSONTyped(json, false);
}

export function UpdateBlueskySettings200ResponseToJSONTyped(value?: UpdateBlueskySettings200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'platform': value['platform'],
        'defaultLangs': value['defaultLangs'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

