/* tslint:disable */
/* eslint-disable */
/**
 * Onepostly API
 * One API for all social media. Authenticate with a workspace API key (`op_…`).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MediaAsset } from './MediaAsset.js';
import {
    MediaAssetFromJSON,
    MediaAssetFromJSONTyped,
    MediaAssetToJSON,
    MediaAssetToJSONTyped,
} from './MediaAsset.js';

/**
 * 
 * @export
 * @interface UploadMedia201Response
 */
export interface UploadMedia201Response {
    /**
     * 
     */
    media: MediaAsset;
}

/**
 * Check if a given object implements the UploadMedia201Response interface.
 */
export function instanceOfUploadMedia201Response(value: object): value is UploadMedia201Response {
    if (!('media' in value) || value['media'] === undefined) return false;
    return true;
}

export function UploadMedia201ResponseFromJSON(json: any): UploadMedia201Response {
    return UploadMedia201ResponseFromJSONTyped(json, false);
}

export function UploadMedia201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadMedia201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'media': MediaAssetFromJSON(json['media']),
    };
}

export function UploadMedia201ResponseToJSON(json: any): UploadMedia201Response {
    return UploadMedia201ResponseToJSONTyped(json, false);
}

export function UploadMedia201ResponseToJSONTyped(value?: UploadMedia201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media': MediaAssetToJSON(value['media']),
    };
}

